# Generated by Django 3.1 on 2021-10-20 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_auto_20210912_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='users.profile')),
                ('voters_no', models.ManyToManyField(blank=True, related_name='options_votes_no', to='users.Profile')),
                ('voters_yes', models.ManyToManyField(blank=True, related_name='options_votes_yes', to='users.Profile')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('order_no', models.SmallIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('Debate', 'Debate'), ('Demand', 'Demand'), ('Announcement', 'Announcement')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField()),
                ('followers', models.ManyToManyField(blank=True, related_name='threads_followed', to='users.Profile')),
                ('known_directly', models.ManyToManyField(related_name='threads_known_directly', to='users.Profile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='communications.topic')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='users.profile')),
                ('options', models.ManyToManyField(blank=True, related_name='threads', to='communications.Option')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='statements_seen', to='users.Profile')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='communications.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('communications.thread',),
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('communications.thread',),
        ),
    ]
