# Generated by Django 4.0.2 on 2022-03-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtag',
            name='kind',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Debate', 'Debate'), ('Demand', 'Demand')], max_length=15),
        ),
    ]
