# Generated by Django 4.0.4 on 2022-04-30 18:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
