# Generated by Django 3.1 on 2021-10-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('communications.thread',),
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('communications.thread',),
        ),
        migrations.AlterField(
            model_name='thread',
            name='kind',
            field=models.CharField(choices=[('Debate', 'Debate'), ('Demand', 'Demand'), ('Announcement', 'Announcement')], max_length=15),
        ),
    ]
