# Generated by Django 4.0.4 on 2022-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_statement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='is_exclusive',
            field=models.BooleanField(default=True),
        ),
    ]
