# Generated by Django 4.0.2 on 2022-03-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_threadtag_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='known_directly',
            new_name='witnesses',
        ),
    ]
