# Generated by Django 3.1 on 2021-10-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_auto_20211020_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
