# Generated by Django 4.0.2 on 2022-03-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('communications', '0003_rename_known_directly_thread_witnesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='witnesses',
            field=models.ManyToManyField(related_name='threads_witnessed', to='users.Profile'),
        ),
    ]
