# Generated by Django 4.0.2 on 2022-03-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_thread_witnesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='witnesses',
            new_name='participants',
        ),
    ]
