# Generated by Django 3.2.8 on 2021-10-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_auto_20211021_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
