# Generated by Django 4.0.2 on 2022-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('communications', '0005_rename_witnesses_thread_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(related_name='threads_participated', to='users.Profile'),
        ),
    ]
