# Generated by Django 3.2.8 on 2021-11-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_auto_20211113_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order_no', 'title']},
        ),
        migrations.AlterField(
            model_name='threadtag',
            name='color',
            field=models.CharField(choices=[('#000000', '#000000'), ('#FF0000', '#FF0000'), ('#00FF00', '#00FF00'), ('#0000FF', '#0000FF'), ('#FFFF00', '#FFFF00'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#C0C0C0', '#C0C0C0'), ('#808080', '#808080'), ('#800000', '#800000'), ('#808000', '#808000'), ('#008000', '#008000'), ('#800080', '#800080'), ('#008080', '#008080'), ('#000080', '#000080')], default='#FF0000', max_length=7),
        ),
    ]
