# Generated by Django 3.2.8 on 2021-11-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_auto_20211113_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadtag',
            options={'ordering': ['kind', 'title', 'author']},
        ),
        migrations.AddField(
            model_name='threadtag',
            name='kind',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Debate', 'Debate'), ('Demand', 'Demand')], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='kind',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Debate', 'Debate'), ('Demand', 'Demand')], max_length=15),
        ),
    ]
