# Generated by Django 3.2.8 on 2021-11-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211023_1358'),
        ('communications', '0008_auto_20211114_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtag',
            name='color',
            field=models.CharField(choices=[('#000000', '#000000'), ('#FF0000', '#FF0000'), ('#00FF00', '#00FF00'), ('#0000FF', '#0000FF'), ('#FFFF00', '#FFFF00'), ('#00FFFF', '#00FFFF'), ('#FF00FF', '#FF00FF'), ('#C0C0C0', '#C0C0C0'), ('#808080', '#808080'), ('#800000', '#800000'), ('#808000', '#808000'), ('#008000', '#008000'), ('#800080', '#800080'), ('#008080', '#008080'), ('#000080', '#000080')], max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='threadtag',
            unique_together={('title', 'author')},
        ),
    ]
