# Generated by Django 3.2.8 on 2021-11-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0009_auto_20211114_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadtag',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
