# Generated by Django 3.2.8 on 2022-01-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0010_alter_threadtag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadtag',
            options={'ordering': ['kind', 'author', 'title']},
        ),
        migrations.AlterField(
            model_name='threadtag',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
