# Generated by Django 3.2.8 on 2022-01-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_options'),
        ('communications', '0011_auto_20220101_1115'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='threadtag',
            unique_together={('title', 'author', 'kind')},
        ),
    ]
