# Generated by Django 3.2.8 on 2022-01-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0012_alter_threadtag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
