# Generated by Django 3.2.8 on 2022-01-09 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0014_alter_thread_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
