# Generated by Django 4.0.2 on 2022-03-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0015_auto_20220109_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debate',
            options={'ordering': ['created_at']},
        ),
    ]
