# Generated by Django 4.0.2 on 2022-03-09 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0016_alter_debate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementStatement',
            fields=[
            ],
            options={
                'verbose_name': 'ANNOUNCEMENT STATEMENT',
                'verbose_name_plural': 'ANNOUNCEMENT STATEMENTS',
                'ordering': ['created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('communications.statement',),
        ),
        migrations.CreateModel(
            name='DebateStatement',
            fields=[
            ],
            options={
                'verbose_name': 'DEBATE STATEMENT',
                'verbose_name_plural': 'DEBATE STATEMENTS',
                'ordering': ['created_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('communications.statement',),
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'ANNOUNCEMENT', 'verbose_name_plural': 'ANNOUNCEMENTS'},
        ),
        migrations.AlterModelOptions(
            name='debate',
            options={'ordering': ['created_at'], 'verbose_name': 'DEBATE', 'verbose_name_plural': 'DEBATES'},
        ),
    ]
