# Generated by Django 2.2.1 on 2019-07-11 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_auto_20190625_1739'), ('users', '0003_auto_20190628_1244'), ('users', '0004_auto_20190628_1245')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('character_name', models.CharField(default='', max_length=50)),
                ('character_status', models.CharField(choices=[('player', 'Postać gracza'), ('npc', 'BN'), ('gm', 'MG')], default='npc', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['character_name'],
            },
        ),
    ]
