# Generated by Django 4.0.2 on 2022-03-25 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rpg_project.utils


class Migration(migrations.Migration):

    # replaces = [('users', '0001_initial'), ('users', '0002_auto_20201225_1757'), ('users', '0003_auto_20210103_0647'), ('users', '0004_auto_20210103_0759'), ('users', '0005_remove_profile_name'), ('users', '0006_auto_20210106_1303'), ('users', '0007_auto_20210106_1613'), ('users', '0008_auto_20210309_1955'), ('users', '0009_auto_20210912_1017'), ('users', '0010_profile_user_fk'), ('users', '0011_auto_20211023_1146'), ('users', '0012_auto_20211023_1222'), ('users', '0013_auto_20211023_1358'), ('users', '0014_alter_profile_options'), ('users', '0015_profile_is_enchanter'), ('users', '0016_profile_user_image')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='profile_pics/profile_default.jpg', null=True, storage=rpg_project.utils.ReplaceFileStorage(), upload_to='profile_pics')),
                ('status', models.CharField(choices=[('gm', 'MG'), ('npc', 'BN'), ('player', 'GRACZ'), ('spectator', 'WIDZ')], default='npc', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('character_name_copy', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
                ('is_enchanter', models.BooleanField(default=False)),
                ('user_image', models.ImageField(blank=True, default='profile_pics/profile_default.jpg', null=True, storage=rpg_project.utils.ReplaceFileStorage(), upload_to='user_pics')),
            ],
            options={
                'ordering': ['-status', '-is_active', 'character_name_copy'],
            },
        ),
    ]
