# Generated by Django 2.2.1 on 2020-03-25 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile_pics/profile_default.jpg', upload_to='profile_pics')),
                ('character_name', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('active_player', 'Gracz'), ('inactive_player', 'Nieaktywny gracz'), ('dead_player', 'Martwy gracz'), ('living_npc', 'Bohater niezależny'), ('dead_npc', 'Martwy bohater niezależny'), ('gm', 'Mistrz gry')], default='living_npc', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'character_name'],
            },
        ),
    ]
