# Generated by Django 3.1 on 2020-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('player_active', 'Gracz'), ('player_inactive', 'Nieaktywny gracz'), ('player_dead', 'Martwy gracz'), ('npc_alive', 'Bohater niezależny'), ('npc_dead', 'Martwy bohater niezależny'), ('gm', 'Mistrz gry')], default='npc_alive', max_length=50),
        ),
    ]
