# Generated by Django 4.0.4 on 2022-05-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-status', '-is_active', 'character__fullname']},
        ),
    ]
