# Generated by Django 4.0.4 on 2022-05-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_enchanter',
        ),
    ]
