# Generated by Django 3.1 on 2020-09-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200926_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('player_active', 'Gracz'), ('player_inactive', 'Nieaktywny gracz'), ('player_dead', 'Martwy gracz'), ('npc_alive', 'BN'), ('npc_dead', 'Martwy BN'), ('gm', 'Mistrz gry')], default='npc_alive', max_length=50),
        ),
    ]
