# Generated by Django 2.2.1 on 2019-07-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190712_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['character_name']},
        ),
    ]
