# Generated by Django 3.1 on 2021-01-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210103_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='character_name',
            new_name='name',
        ),
    ]
