# Generated by Django 2.2.1 on 2019-07-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190716_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['character_status', 'character_name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='character_status',
            field=models.CharField(choices=[('active_player', 'Postać gracza'), ('inactive_player', 'Dawna postać gracza'), ('npc', 'Bohater niezależny'), ('gm', 'Mistrz gry')], default='npc', max_length=20),
        ),
    ]
