# Generated by Django 4.0.4 on 2022-06-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_image_alter_profile_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='character_name_copy',
        ),
    ]
