# Generated by Django 3.1 on 2020-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200926_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['status', 'character_name']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('1_gm', 'Mistrz gry'), ('2_player_active', 'Gracz'), ('3_player_inactive', 'Nieaktywny gracz'), ('4_player_dead', 'Martwy gracz'), ('5_npc_alive', 'BN'), ('6_npc_dead', 'Martwy BN')], default='5_npc_alive', max_length=50),
        ),
    ]
