# Generated by Django 3.1 on 2020-09-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200926_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('2_player_active', 'Gracz'), ('3_player_inactive', 'Nieaktywny gracz'), ('4_player_dead', 'Martwy gracz'), ('5_npc_alive', 'BN'), ('6_npc_dead', 'Martwy BN'), ('gm', 'Mistrz gry')], default='5_npc_alive', max_length=50),
        ),
    ]
