# Generated by Django 3.1 on 2020-09-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200926_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('1_player_active', 'Gracz'), ('2_player_inactive', 'Nieaktywny gracz'), ('3_player_dead', 'Martwy gracz'), ('4_npc_alive', 'BN'), ('5_npc_dead', 'Martwy BN'), ('gm', 'Mistrz gry')], default='5_npc_alive', max_length=50),
        ),
    ]
