# Generated by Django 3.1 on 2020-09-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200926_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active_player', 'Gracz'), ('inactive_player', 'Nieaktywny gracz'), ('dead_player', 'Martwy gracz'), ('living_npc', 'Bohater niezależny'), ('dead_npc', 'Martwy bohater niezależny'), ('gm', 'Mistrz gry')], default='5_npc_alive', max_length=50),
        ),
    ]
