# Generated by Django 3.1 on 2021-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210309_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('gm', 'MG'), ('npc', 'BN'), ('player', 'GRACZ'), ('spectator', 'WIDZ')], default='npc', max_length=50),
        ),
    ]
