# Generated by Django 2.2.1 on 2019-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190718_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='character_status',
            field=models.CharField(choices=[('active_player', 'Postać gracza'), ('inactive_player', 'Dawna postać gracza'), ('dead_player', 'Martwa postać gracza'), ('living_npc', 'Bohater niezależny'), ('dead_npc', 'Martwy bohater niezależny'), ('gm', 'Mistrz gry')], default='npc', max_length=20),
        ),
    ]
