# Generated by Django 2.2.1 on 2019-07-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190718_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['character_status', 'character_name']},
        ),
    ]
