# Generated by Django 3.1 on 2020-09-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200926_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active_player', 'Gracz'), ('inactive_player', 'Nieaktywny gracz'), ('dead_player', 'Martwy gracz'), ('living_npc', 'BN'), ('dead_npc', 'Martwy BN'), ('gm', 'MG')], default='living_npc', max_length=50),
        ),
    ]
