# Generated by Django 2.2.1 on 2019-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190718_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='character_status',
            field=models.CharField(choices=[('active_player', 'Postać gracza'), ('inactive_player', 'Nieaktywna postać gracza'), ('dead_player', 'Martwa postać gracza'), ('living_npc', 'Bohater niezależny'), ('dead_npc', 'Martwy bohater niezależny'), ('gm', 'Mistrz gry')], default='npc', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default_profile.jpg', upload_to='profile_pics'),
        ),
    ]
