# Generated by Django 2.2.1 on 2019-08-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190726_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='character_status',
            field=models.CharField(choices=[('active_player', 'Postać gracza'), ('inactive_player', 'Nieaktywna postać gracza'), ('dead_player', 'Martwa postać gracza'), ('living_npc', 'Bohater niezależny'), ('dead_npc', 'Martwy bohater niezależny'), ('gm', 'Mistrz gry')], default='living_npc', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/profile_default.jpg', upload_to='profile_pics'),
        ),
    ]
