# Generated by Django 4.0.2 on 2022-02-20 11:16

from django.db import migrations, models
import rpg_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_is_enchanter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.ImageField(blank=True, default='profile_pics/profile_default.jpg', null=True, storage=rpg_project.utils.ReplaceFileStorage(), upload_to='user_pics'),
        ),
    ]
