# Generated by Django 3.1 on 2021-02-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_auto_20210205_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biographypacket',
            options={'ordering': ['order_no', 'sorting_name']},
        ),
        migrations.AddField(
            model_name='biographypacket',
            name='order_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nr porządkowy'),
        ),
    ]
