# Generated by Django 3.1 on 2021-02-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0011_auto_20210221_1423'),
        ('knowledge', '0010_auto_20210220_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='biographypacket',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='biography_packets', to='imaginarion.Picture'),
        ),
        migrations.AlterField(
            model_name='biographypacket',
            name='order_no',
            field=models.SmallIntegerField(default=1),
        ),
    ]
