# Generated by Django 3.1 on 2021-09-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0012_mappacket_picture_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappacket',
            name='pictures',
        ),
    ]
