# Generated by Django 3.1 on 2021-09-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0012_pictureset'),
        ('knowledge', '0013_remove_mappacket_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepacket',
            name='picture_sets',
            field=models.ManyToManyField(blank=True, related_name='knowledge_packets', to='imaginarion.PictureSet'),
        ),
    ]
