# Generated by Django 3.1 on 2021-09-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0016_biographypacket_picture_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biographypacket',
            name='pictures',
        ),
    ]
