# Generated by Django 4.0.2 on 2022-03-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('knowledge', '0001_initial'), ('knowledge', '0002_auto_20201225_1400'), ('knowledge', '0003_auto_20201226_2252'), ('knowledge', '0004_auto_20201228_2101'), ('knowledge', '0005_biographypacket_show_in_prosoponomikon'), ('knowledge', '0006_remove_biographypacket_show_in_prosoponomikon'), ('knowledge', '0007_auto_20210205_0001'), ('knowledge', '0008_auto_20210220_1110'), ('knowledge', '0009_auto_20210220_1118'), ('knowledge', '0010_auto_20210220_1123'), ('knowledge', '0011_auto_20210221_1423'), ('knowledge', '0012_mappacket_picture_sets'), ('knowledge', '0013_remove_mappacket_pictures'), ('knowledge', '0014_knowledgepacket_picture_sets'), ('knowledge', '0015_remove_knowledgepacket_pictures'), ('knowledge', '0016_biographypacket_picture_sets'), ('knowledge', '0017_remove_biographypacket_pictures'), ('knowledge', '0018_auto_20211017_1835')]

    initial = True

    dependencies = [
        ('rules', '0001_initial_squashed'),
        ('imaginarion', '0001_initial_squashed'),
        ('users', '0001_initial'),
        # ('imaginarion', '0012_pictureset'),
        # ('imaginarion', '0001_initial'),
        # ('imaginarion', '0011_auto_20210221_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('acquired_by', models.ManyToManyField(blank=True, related_name='biography_packets', to='users.Profile')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_bio_packets', to='users.profile')),
                ('order_no', models.SmallIntegerField(default=1)),
                ('picture_sets', models.ManyToManyField(blank=True, related_name='biography_packets', to='imaginarion.PictureSet')),
            ],
            options={
                'ordering': ['order_no', 'sorting_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DialoguePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['sorting_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('acquired_by', models.ManyToManyField(blank=True, related_name='knowledge_packets', to='users.Profile')),
                ('skills', models.ManyToManyField(related_name='knowledge_packets', to='rules.Skill')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_kn_packets', to='users.profile')),
                ('picture_sets', models.ManyToManyField(blank=True, related_name='knowledge_packets', to='imaginarion.PictureSet')),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
        migrations.CreateModel(
            name='MapPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('acquired_by', models.ManyToManyField(blank=True, related_name='map_packets', to='users.Profile')),
                ('text', models.TextField(blank=True, null=True)),
                ('picture_sets', models.ManyToManyField(related_name='map_packets', to='imaginarion.PictureSet')),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
    ]
