# Generated by Django 2.2.1 on 2020-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imaginarion', '0001_initial'),
        ('users', '0001_initial'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('acquired_by', models.ManyToManyField(blank=True, related_name='kn_packets', to='users.Profile')),
                ('pictures', models.ManyToManyField(blank=True, related_name='knowledge_packets', to='imaginarion.Picture')),
                ('skills', models.ManyToManyField(related_name='knowledge_packets', to='rules.Skill')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
