# Generated by Django 4.0.2 on 2022-03-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('imaginarion', '0001_initial_squashed'),
        ('users', '0001_initial_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiographyPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('acquired_by', models.ManyToManyField(blank=True, related_name='biography_packets', to='users.Profile')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_bio_packets', to='users.profile')),
                ('order_no', models.SmallIntegerField(default=1)),
                ('picture_sets', models.ManyToManyField(blank=True, related_name='biography_packets', to='imaginarion.PictureSet')),
            ],
            options={
                'ordering': ['order_no', 'sorting_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DialoguePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['sorting_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgePacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('acquired_by', models.ManyToManyField(blank=True, related_name='knowledge_packets', to='users.Profile')),
                ('skills', models.ManyToManyField(related_name='knowledge_packets', to='rules.Skill')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_kn_packets', to='users.profile')),
                ('picture_sets', models.ManyToManyField(blank=True, related_name='knowledge_packets', to='imaginarion.PictureSet')),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
        migrations.CreateModel(
            name='MapPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('acquired_by', models.ManyToManyField(blank=True, related_name='map_packets', to='users.Profile')),
                ('text', models.TextField(blank=True, null=True)),
                ('picture_sets', models.ManyToManyField(related_name='map_packets', to='imaginarion.PictureSet')),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
    ]
