# Generated by Django 4.0.4 on 2022-05-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biographypacket',
            options={'ordering': ['order_no', 'title']},
        ),
        migrations.AlterModelOptions(
            name='dialoguepacket',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='knowledgepacket',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='mappacket',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='biographypacket',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='dialoguepacket',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='knowledgepacket',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='mappacket',
            name='sorting_name',
        ),
    ]
