# Generated by Django 2.2.1 on 2020-03-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepacket',
            name='acquired_by',
            field=models.ManyToManyField(blank=True, related_name='knowledge_packets', to='users.Profile'),
        ),
    ]
