# Generated by Django 4.0.4 on 2022-08-26 14:55

from django.db import migrations
import rpg_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_biographypacket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biographypacket',
            options={'ordering': ['order_no', rpg_project.utils.OrderByPolish('title')]},
        ),
        migrations.AlterModelOptions(
            name='dialoguepacket',
            options={'ordering': [rpg_project.utils.OrderByPolish('title')]},
        ),
        migrations.AlterModelOptions(
            name='knowledgepacket',
            options={'ordering': [rpg_project.utils.OrderByPolish('title')]},
        ),
        migrations.AlterModelOptions(
            name='mappacket',
            options={'ordering': [rpg_project.utils.OrderByPolish('title')]},
        ),
    ]
