# Generated by Django 2.2.1 on 2020-04-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_auto_20200327_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgepacket',
            options={'ordering': ['sorting_name']},
        ),
    ]
