# Generated by Django 3.1 on 2020-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0001_initial'),
        ('knowledge', '0003_auto_20201226_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgepacket',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='knowledge_packets', to='imaginarion.Picture', verbose_name='Obrazy [opcjonalnie]'),
        ),
        migrations.AlterField(
            model_name='mappacket',
            name='pictures',
            field=models.ManyToManyField(related_name='map_packets', to='imaginarion.Picture', verbose_name='Obrazy [opcjonalnie]'),
        ),
    ]
