# Generated by Django 3.1 on 2020-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0005_auto_20200915_1828'),
        ('users', '0001_initial'),
        ('knowledge', '0003_auto_20200419_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('acquired_by', models.ManyToManyField(blank=True, related_name='map_packets', to='users.Profile')),
                ('pictures', models.ManyToManyField(blank=True, related_name='map_packets', to='imaginarion.Picture')),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
    ]
