# Generated by Django 4.0.4 on 2022-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_alter_biographypacket_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Odsyłacz',
                'verbose_name_plural': 'Odsyłacze',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='knowledgepacket',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='knowledge_packets', to='knowledge.reference'),
        ),
    ]
