# Generated by Django 3.1 on 2020-10-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0005_auto_20200915_1828'),
        ('knowledge', '0004_mappacket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappacket',
            name='pictures',
            field=models.ManyToManyField(related_name='map_packets', to='imaginarion.Picture'),
        ),
    ]
