# Generated by Django 4.0.4 on 2022-12-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_reference_knowledgepacket_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ['title']},
        ),
    ]
