# Generated by Django 3.1 on 2020-11-08 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('knowledge', '0005_auto_20201031_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerKnowledgePacket',
            fields=[
                ('knowledgepacket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='knowledge.knowledgepacket')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_kn_packets', to='users.profile')),
            ],
            bases=('knowledge.knowledgepacket',),
        ),
    ]
