# Generated by Django 3.1 on 2021-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0003_auto_20210121_1949'),
        ('knowledge', '0006_remove_biographypacket_show_in_prosoponomikon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographypacket',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='dialoguepacket',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='knowledgepacket',
            name='pictures',
            field=models.ManyToManyField(blank=True, related_name='knowledge_packets', to='imaginarion.Picture', verbose_name='Obrazy'),
        ),
        migrations.AlterField(
            model_name='knowledgepacket',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='mappacket',
            name='pictures',
            field=models.ManyToManyField(related_name='map_packets', to='imaginarion.Picture', verbose_name='Obrazy'),
        ),
        migrations.AlterField(
            model_name='mappacket',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Treść'),
        ),
    ]
