# Generated by Django 3.1 on 2020-11-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200926_1248'),
        ('knowledge', '0007_delete_playerknowledgepacket'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepacket',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authored_kn_packets', to='users.profile'),
        ),
    ]
