# Generated by Django 3.1 on 2021-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_auto_20210220_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographypacket',
            name='order_no',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nr porządkowy'),
        ),
    ]
