# Generated by Django 3.1 on 2021-09-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0012_pictureset'),
        ('knowledge', '0011_auto_20210221_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappacket',
            name='picture_sets',
            field=models.ManyToManyField(related_name='map_packets', to='imaginarion.PictureSet'),
        ),
    ]
