# Generated by Django 3.1 on 2021-09-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0012_pictureset'),
        ('knowledge', '0015_remove_knowledgepacket_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='biographypacket',
            name='picture_sets',
            field=models.ManyToManyField(blank=True, related_name='biography_packets', to='imaginarion.PictureSet'),
        ),
    ]
