# Generated by Django 3.1 on 2021-10-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_squashed_0005_auto_20211017_1835'),
        ('knowledge', '0017_remove_biographypacket_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographypacket',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biographypacket',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dialoguepacket',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dialoguepacket',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgepacket',
            name='skills',
            field=models.ManyToManyField(related_name='knowledge_packets', to='rules.Skill'),
        ),
        migrations.AlterField(
            model_name='knowledgepacket',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='knowledgepacket',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mappacket',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mappacket',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
