runtime: python311

handlers:
# This configures Google App Engine to serve the files in the app's static directory.
- url: /static
  static_dir: static/


env_variables:
    APPENGINE_URL: https://hyllemath.lm.r.appspot.com

