# Generated by Django 3.1 on 2020-11-27 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('news', '0001_initial'), ('news', '0002_auto_20200708_0641')]

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_pics')),
                ('allowed_profiles', models.ManyToManyField(related_name='allowed_news', to='users.Profile')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_news', to='users.Profile')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='news_seen', to='users.Profile')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(max_length=4000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addressees', models.ManyToManyField(related_name='surveys_received', to='users.Profile')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys_authored', to=settings.AUTH_USER_MODEL)),
                ('seen_by', models.ManyToManyField(blank=True, related_name='surveys_seen', to='users.Profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_options_authored', to=settings.AUTH_USER_MODEL)),
                ('no_voters', models.ManyToManyField(blank=True, related_name='survey_no_votes', to='users.Profile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_options', to='news.survey')),
                ('yes_voters', models.ManyToManyField(blank=True, related_name='survey_yes_votes', to='users.Profile')),
            ],
            options={
                'ordering': ['option_text'],
            },
        ),
        migrations.CreateModel(
            name='NewsAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_answers', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_answers', to='news.news')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='news_answers_seen', to='users.Profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to=settings.AUTH_USER_MODEL)),
                ('seen_by', models.ManyToManyField(blank=True, related_name='survey_answers_seen', to='users.Profile')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='news.survey')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
