# Generated by Django 2.2.1 on 2019-07-11 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('news', '0001_initial'), ('news', '0002_auto_20190625_1739'), ('news', '0003_auto_20190628_1244'), ('news', '0004_auto_20190628_1245'), ('news', '0005_remove_news_allowed_users'), ('news', '0006_news_allowed_profiles'), ('news', '0007_auto_20190706_1152'), ('news', '0008_news_date_posted'), ('news', '0009_news_image'), ('news', '0010_auto_20190706_1634'), ('news', '0011_response'), ('news', '0012_auto_20190709_1759'), ('news', '0013_auto_20190710_1430'), ('news', '0014_auto_20190710_1735')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_auto_20190628_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('text', models.TextField(max_length=4000)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL)),
                ('allowed_profiles', models.ManyToManyField(limit_choices_to={'character_status': 'player'}, related_name='allowed_news', to='users.Profile')),
                ('date_posted', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_pics')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='news.News')),
            ],
        ),
    ]
