# Generated by Django 2.2.1 on 2019-07-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_squashed_0014_auto_20190710_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
