# Generated by Django 2.2.1 on 2020-07-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='newsanswer',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='surveyanswer',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='newsanswer',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='surveyanswer',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
