# Generated by Django 2.2.1 on 2019-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190712_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='allowed_profiles',
            field=models.ManyToManyField(limit_choices_to={'character_status': 'active_player'}, related_name='allowed_news', to='users.Profile'),
        ),
    ]
