# Generated by Django 3.1 on 2021-01-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210106_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newsanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='author',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='author',
        ),
    ]
