# Generated by Django 3.1 on 2021-10-15 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210912_1017'),
        ('news', '0008_auto_20210925_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='allowed_profiles',
            field=models.ManyToManyField(related_name='allowed_news', to='users.Profile', verbose_name='Adresaci'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.topic', verbose_name='Temat'),
        ),
        migrations.AlterField(
            model_name='newsanswer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=77, verbose_name='Temat'),
        ),
    ]
