# Generated by Django 3.1 on 2021-10-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210912_1017'),
        ('news', '0009_auto_20211015_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='allowed_profiles',
            field=models.ManyToManyField(related_name='allowed_news', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
