# Generated by Django 3.1 on 2021-10-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_news_seen_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order_no', 'title']},
        ),
        migrations.AddField(
            model_name='topic',
            name='order_no',
            field=models.SmallIntegerField(default=100),
        ),
    ]
