# Generated by Django 3.1 on 2021-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20211015_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsanswer',
            name='survey_options',
            field=models.ManyToManyField(blank=True, related_name='threads', to='news.SurveyOption'),
        ),
    ]
