# Generated by Django 3.1 on 2021-10-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_newsanswer_survey_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='seen_by',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyoption',
            name='survey',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
    ]
