# Generated by Django 3.2.8 on 2022-01-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20211019_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanswer',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
