# Generated by Django 3.1 on 2020-12-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imaginarion', '0001_initial'),
        ('knowledge', '0002_auto_20201225_1400'),
        ('users', '0002_auto_20201225_1757'),
        ('toponomikon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('knowledge_packets', models.ManyToManyField(blank=True, related_name='character_groups', to='knowledge.KnowledgePacket')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_short', models.CharField(blank=True, max_length=250, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('biography_packets', models.ManyToManyField(blank=True, related_name='characters', to='knowledge.BiographyPacket')),
                ('birth_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characters_born', to='toponomikon.location')),
                ('character_groups', models.ManyToManyField(blank=True, related_name='characters', to='prosoponomikon.CharacterGroup')),
                ('dialogue_packets', models.ManyToManyField(blank=True, related_name='characters', to='knowledge.DialoguePacket')),
                ('known_directly', models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='characters_known_directly', to='users.Profile')),
                ('known_indirectly', models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='characters_known_indirectly', to='users.Profile')),
                ('locations', models.ManyToManyField(blank=True, related_name='characters', to='toponomikon.Location')),
                ('pictures', models.ManyToManyField(blank=True, related_name='characters', to='imaginarion.Picture')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NonPlayerCharacter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.character',),
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.character',),
        ),
    ]
