# Generated by Django 3.1 on 2020-12-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0002_auto_20201225_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='description_long',
            new_name='descr_occupation',
        ),
        migrations.RenameField(
            model_name='character',
            old_name='description_short',
            new_name='descr_origin',
        ),
    ]
