# Generated by Django 3.1 on 2020-12-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0005_character_descr_for_gm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['sorting_name']},
        ),
        migrations.AddField(
            model_name='character',
            name='sorting_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
