# Generated by Django 3.1 on 2021-01-03 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201225_1757'),
        ('toponomikon', '0001_initial'),
        ('imaginarion', '0001_initial'),
        ('prosoponomikon', '0009_auto_20201226_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='descr_for_gm',
            new_name='description_main',
        ),
        migrations.RemoveField(
            model_name='character',
            name='descr_occupation',
        ),
        migrations.RemoveField(
            model_name='character',
            name='descr_origin',
        ),
        migrations.RemoveField(
            model_name='character',
            name='descr_psychophysical',
        ),
        migrations.RemoveField(
            model_name='character',
            name='locations',
        ),
        migrations.AddField(
            model_name='character',
            name='picture_main',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imaginarion.picture'),
        ),
        migrations.AddField(
            model_name='character',
            name='visited_locations',
            field=models.ManyToManyField(blank=True, related_name='visiting_characters', to='toponomikon.Location'),
        ),
        migrations.AlterField(
            model_name='character',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='users.profile'),
        ),
    ]
