# Generated by Django 3.1 on 2021-01-03 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_auto_20201228_2101'),
        ('imaginarion', '0001_initial'),
        ('users', '0002_auto_20201225_1757'),
        ('toponomikon', '0001_initial'),
        ('prosoponomikon', '0010_auto_20210103_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description_main', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('biography_packets', models.ManyToManyField(blank=True, related_name='personas', to='knowledge.BiographyPacket')),
                ('birth_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas_born', to='toponomikon.location')),
                ('dialogue_packets', models.ManyToManyField(blank=True, related_name='personas', to='knowledge.DialoguePacket')),
                ('known_directly', models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='personas_known_directly', to='users.Profile')),
                ('known_indirectly', models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='personas_known_indirectly', to='users.Profile')),
                ('picture_main', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imaginarion.picture')),
                ('pictures', models.ManyToManyField(blank=True, related_name='personas', to='imaginarion.Picture')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='users.profile')),
                ('visited_locations', models.ManyToManyField(blank=True, related_name='visiting_personas', to='toponomikon.Location')),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nazwa grupy')),
                ('order_no', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numer porządkowy grupy [opcjonalnie]:')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_groups_authored', to='users.profile')),
                ('default_knowledge_packets', models.ManyToManyField(blank=True, related_name='persona_group_defaults', to='knowledge.KnowledgePacket', verbose_name='Domyślne umiejętności zgrupowanych postaci')),
                ('personas', models.ManyToManyField(related_name='persona_groups', to='prosoponomikon.Persona', verbose_name='Zgrupowane postacie')),
            ],
            options={
                'ordering': ['order_no', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='biography_packets',
        ),
        migrations.RemoveField(
            model_name='character',
            name='birth_location',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dialogue_packets',
        ),
        migrations.RemoveField(
            model_name='character',
            name='known_directly',
        ),
        migrations.RemoveField(
            model_name='character',
            name='known_indirectly',
        ),
        migrations.RemoveField(
            model_name='character',
            name='picture_main',
        ),
        migrations.RemoveField(
            model_name='character',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='character',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='character',
            name='visited_locations',
        ),
        migrations.RemoveField(
            model_name='charactergroup',
            name='author',
        ),
        migrations.RemoveField(
            model_name='charactergroup',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='charactergroup',
            name='default_knowledge_packets',
        ),
        migrations.DeleteModel(
            name='NonPlayerCharacter',
        ),
        migrations.DeleteModel(
            name='PlayerCharacter',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='CharacterGroup',
        ),
        migrations.CreateModel(
            name='NonPlayerPersona',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.persona',),
        ),
        migrations.CreateModel(
            name='PlayerPersona',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.persona',),
        ),
    ]
