# Generated by Django 3.1 on 2021-01-03 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210103_0647'),
        ('prosoponomikon', '0011_auto_20210103_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to='users.profile'),
        ),
    ]
