# Generated by Django 3.1 on 2021-01-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0017_character_charactergroup_npccharacter_playercharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='biography_packets',
        ),
        migrations.RemoveField(
            model_name='character',
            name='birth_location',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dialogue_packets',
        ),
        migrations.RemoveField(
            model_name='character',
            name='frequented_locations',
        ),
        migrations.RemoveField(
            model_name='character',
            name='known_directly',
        ),
        migrations.RemoveField(
            model_name='character',
            name='known_indirectly',
        ),
        migrations.RemoveField(
            model_name='character',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='character',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='charactergroup',
            name='author',
        ),
        migrations.RemoveField(
            model_name='charactergroup',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='charactergroup',
            name='default_knowledge_packets',
        ),
        migrations.DeleteModel(
            name='NPCCharacter',
        ),
        migrations.DeleteModel(
            name='PlayerCharacter',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='CharacterGroup',
        ),
    ]
