# Generated by Django 3.1 on 2021-01-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0019_character_charactergroup_npccharacter_playercharacter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='biography_packets',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='birth_location',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='dialogue_packets',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='frequented_locations',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='known_directly',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='known_indirectly',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='personagroup',
            name='author',
        ),
        migrations.RemoveField(
            model_name='personagroup',
            name='default_knowledge_packets',
        ),
        migrations.RemoveField(
            model_name='personagroup',
            name='personas',
        ),
        migrations.DeleteModel(
            name='NPCPersona',
        ),
        migrations.DeleteModel(
            name='PlayerPersona',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='PersonaGroup',
        ),
    ]
