# Generated by Django 3.1 on 2021-01-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210106_1613'),
        ('prosoponomikon', '0020_auto_20210117_1651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charactergroup',
            unique_together={('name', 'author')},
        ),
    ]
