# Generated by Django 3.1 on 2021-02-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0003_auto_20210106_1613'),
        ('prosoponomikon', '0026_auto_20210221_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameContinuum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=250)),
                ('is_ancient', models.BooleanField()),
                ('locations', models.ManyToManyField(blank=True, related_name='names', to='toponomikon.Location')),
                ('name_continuum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name_forms', to='prosoponomikon.namecontinuum')),
            ],
        ),
    ]
