# Generated by Django 3.1 on 2021-02-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0027_namecontinuum_nameform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameform',
            name='is_ancient',
            field=models.BooleanField(default=False),
        ),
    ]
