# Generated by Django 3.1 on 2021-02-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0028_auto_20210221_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nameform',
            options={'ordering': ['form']},
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
