# Generated by Django 3.1 on 2021-02-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0003_auto_20210106_1613'),
        ('prosoponomikon', '0033_auto_20210221_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=250)),
                ('locations', models.ManyToManyField(blank=True, related_name='family_names', to='toponomikon.Location')),
            ],
            options={
                'ordering': ['form'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='family_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='prosoponomikon.familyname'),
        ),
    ]
