# Generated by Django 3.1 on 2021-02-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0034_auto_20210223_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameform',
            name='type',
            field=models.CharField(choices=[('Mężczyźni', 'MALE'), ('Kobiety', 'FEMALE'), ('Duchy i demony', 'DAEMON')], default='male', max_length=20),
        ),
    ]
