# Generated by Django 3.1 on 2021-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20210106_1613'),
        ('knowledge', '0011_auto_20210221_1423'),
        ('prosoponomikon', '0036_auto_20210225_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactergroup',
            name='default_skills',
            field=models.ManyToManyField(blank=True, related_name='character_group_defaults', to='rules.Skill', verbose_name='Domyślne umiejętności NPC w grupie'),
        ),
        migrations.AlterField(
            model_name='charactergroup',
            name='default_knowledge_packets',
            field=models.ManyToManyField(blank=True, related_name='character_group_defaults', to='knowledge.KnowledgePacket', verbose_name='Domyślne pakiety wiedzy NPC w grupie'),
        ),
    ]
