# Generated by Django 3.1 on 2021-03-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0003_auto_20210106_1613'),
        ('prosoponomikon', '0041_auto_20210305_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffixGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affix', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuxiliaryNameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('social_info', models.TextField(help_text='Social group indication if no location')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='toponomikon.location')),
            ],
        ),
        migrations.RenameField(
            model_name='namegroup',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='name',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='name',
            name='name_continuum',
        ),
        migrations.RemoveField(
            model_name='name',
            name='name_groups',
        ),
        migrations.DeleteModel(
            name='NameContinuum',
        ),
        migrations.AddField(
            model_name='affixgroup',
            name='name_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prosoponomikon.namegroup'),
        ),
        migrations.AddField(
            model_name='name',
            name='affix_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prosoponomikon.affixgroup'),
        ),
        migrations.AddField(
            model_name='name',
            name='auxiliary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prosoponomikon.auxiliarynamegroup'),
        ),
    ]
