# Generated by Django 3.1 on 2021-03-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0043_auto_20210305_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='type',
        ),
        migrations.AddField(
            model_name='affixgroup',
            name='type',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('DAEMON', 'DAEMON')], default='male', max_length=20),
        ),
    ]
