# Generated by Django 3.1 on 2021-03-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0045_auto_20210305_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affixgroup',
            options={'ordering': ['name_group', 'type', 'affix']},
        ),
        migrations.AlterUniqueTogether(
            name='affixgroup',
            unique_together={('affix', 'type', 'name_group')},
        ),
    ]
