# Generated by Django 3.1 on 2021-03-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0053_auto_20210312_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namegroup',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
