# Generated by Django 3.1 on 2021-03-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0054_auto_20210312_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyname',
            name='form',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
