# Generated by Django 3.1 on 2021-03-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0057_namegroup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namegroup',
            name='type',
            field=models.CharField(choices=[('local', 'local'), ('racial', 'racial'), ('social', 'social')], max_length=50),
        ),
    ]
