# Generated by Django 3.1 on 2021-03-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0058_auto_20210319_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affixgroup',
            name='type',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNISEX', 'UNISEX')], default='male', max_length=20),
        ),
    ]
