# Generated by Django 3.1 on 2021-03-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0060_familyname_auxiliary_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyname',
            name='auxiliary_group',
        ),
    ]
