# Generated by Django 3.1 on 2021-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0063_familyname_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affixgroup',
            name='type',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNISEX', 'UNISEX')], default='MALE', max_length=20),
        ),
    ]
