# Generated by Django 3.1 on 2021-10-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0018_auto_20211017_1835'),
        ('rules', '0005_auto_20211017_1835'),
        ('prosoponomikon', '0066_remove_character_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactergroup',
            name='characters',
            field=models.ManyToManyField(related_name='character_groups', to='prosoponomikon.Character'),
        ),
        migrations.AlterField(
            model_name='charactergroup',
            name='default_knowledge_packets',
            field=models.ManyToManyField(blank=True, related_name='character_group_defaults', to='knowledge.KnowledgePacket'),
        ),
        migrations.AlterField(
            model_name='charactergroup',
            name='default_skills',
            field=models.ManyToManyField(blank=True, related_name='character_group_defaults', to='rules.Skill'),
        ),
        migrations.AlterField(
            model_name='charactergroup',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='charactergroup',
            name='order_no',
            field=models.SmallIntegerField(default=1),
        ),
    ]
