# Generated by Django 4.0.2 on 2022-03-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0068_character_professions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterGroup',
        ),
    ]
