# Generated by Django 2.2.1 on 2019-07-11 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('timeline', '0001_initial'), ('timeline', '0002_auto_20190709_1409'), ('timeline', '0003_auto_20190709_1413'), ('timeline', '0004_auto_20190709_1413'), ('timeline', '0005_auto_20190709_1417'), ('timeline', '0006_auto_20190709_1419'), ('timeline', '0007_auto_20190709_1500'), ('timeline', '0008_auto_20190709_1501'), ('timeline', '0009_auto_20190709_1531'), ('timeline', '0010_auto_20190709_1543'), ('timeline', '0011_auto_20190709_1603'), ('timeline', '0012_auto_20190709_1622'), ('timeline', '0013_auto_20190709_1759'), ('timeline', '0014_auto_20190710_1430'), ('timeline', '0015_auto_20190710_1731'), ('timeline', '0016_auto_20190710_1749')]

    initial = True

    dependencies = [
        ('users', '0004_auto_20190628_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('season', models.CharField(choices=[('1', 'Wiosna'), ('2', 'Lato'), ('3', 'Jesień'), ('4', 'Zima')], max_length=100)),
                ('day_start', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('day_end', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('thread', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=4000)),
                ('location1', models.CharField(max_length=200)),
                ('location2', models.CharField(max_length=200)),
                ('game_no', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('informed', models.ManyToManyField(blank=True, limit_choices_to={'character_status': 'player'}, related_name='events_informed', to='users.Profile')),
                ('participants', models.ManyToManyField(blank=True, limit_choices_to={'character_status': 'player'}, related_name='events_participated', to='users.Profile')),
            ],
            options={
                'ordering': ['year', 'season', 'day_start', 'day_end', 'thread'],
            },
        ),
    ]
