# Generated by Django 2.2.1 on 2019-07-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('day_start', models.CharField(max_length=100)),
                ('day_end', models.CharField(blank=True, max_length=100, null=True)),
                ('thread', models.TextField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('location1', models.CharField(max_length=100)),
                ('location2', models.CharField(max_length=100)),
                ('game_no', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['-day_start'],
            },
        ),
    ]
