# Generated by Django 2.2.1 on 2019-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0003_auto_20190718_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_individual',
            field=models.BooleanField(default=False),
        ),
    ]
