# Generated by Django 3.1 on 2021-01-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0005_remark_author2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='author',
        ),
    ]
