# Generated by Django 3.1 on 2021-01-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0006_remove_remark_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='author2',
            new_name='author',
        ),
    ]
