# Generated by Django 3.1 on 2021-01-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210106_1613'),
        ('debates', '0007_auto_20210106_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='known_directly',
            field=models.ManyToManyField(help_text='\n            ***Aby zaznaczyć wiele postaci - użyj CTRL albo SHIFT.<br><br>\n            1) Włączaj tylko postacie znajdujące się w pobliżu w chwili\n                zakończenia ostatniej sesji.<br>\n            2) Postacie w pobliżu niewłączone do narady mogą to zauważyć.<br>\n            3) Jeśli chcesz zaczekać na sposobny moment, powiadom MG.<br>\n            4) Jeśli na liście brakuje postaci, powiadom MG.<br><br>\n        ', related_name='debates_known_directly', to='users.Profile', verbose_name='Uczestnicy'),
        ),
    ]
