# Generated by Django 3.1 on 2021-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0008_auto_20210106_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics', verbose_name='Obraz'),
        ),
    ]
