# Generated by Django 3.1 on 2021-02-20 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0009_auto_20210205_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debate',
            options={'ordering': ['created_at']},
        ),
    ]
