# Generated by Django 3.1 on 2021-09-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0011_auto_20210925_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='is_individual',
            new_name='is_exclusive',
        ),
    ]
