# Generated by Django 3.1 on 2021-09-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0012_auto_20210925_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='is_exclusive',
            field=models.BooleanField(verbose_name='Narada zamknięta?'),
        ),
    ]
