# Generated by Django 3.1 on 2021-09-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210912_1017'),
        ('debates', '0013_auto_20210925_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='known_directly',
            field=models.ManyToManyField(related_name='debates_known_directly', to='users.Profile', verbose_name='Uczestnicy'),
        ),
    ]
