# Generated by Django 3.1 on 2021-10-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210912_1017'),
        ('debates', '0014_auto_20210925_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='is_exclusive',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='debate',
            name='known_directly',
            field=models.ManyToManyField(related_name='debates_known_directly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='title',
            field=models.CharField(max_length=77, unique=True),
        ),
        migrations.AlterField(
            model_name='remark',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=77, unique=True),
        ),
    ]
