# Generated by Django 3.1 on 2021-10-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0015_auto_20211015_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debate',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
