# Generated by Django 3.1 on 2021-10-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0016_auto_20211015_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order_no',
            field=models.SmallIntegerField(default=100),
        ),
    ]
