# Generated by Django 3.2.8 on 2022-01-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0017_topic_order_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='author',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='debate',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='seen_by',
        ),
        migrations.DeleteModel(
            name='Debate',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
