# Generated by Django 2.2.1 on 2020-03-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('imaginarion', '0001_initial'),
        ('rules', '0001_initial'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_packets', models.ManyToManyField(blank=True, related_name='characters', to='knowledge.KnowledgePacket')),
                ('pictures', models.ManyToManyField(blank=True, related_name='characters_pics', to='imaginarion.Picture')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('skill_levels_acquired', models.ManyToManyField(blank=True, related_name='acquired_by_characters', to='rules.SkillLevel')),
                ('synergy_levels_acquired', models.ManyToManyField(blank=True, related_name='acquired_by_characters', to='rules.SynergyLevel')),
            ],
            options={
                'ordering': ['profile'],
            },
        ),
    ]
