# Generated by Django 3.1 on 2020-11-29 08:06

from django.db import migrations, models
import django.db.models.deletion
import rpg_project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('npc', 'NPC'), ('topoi', 'TOPOI'), ('varia', 'VARIA')], max_length=5)),
                ('path', models.TextField(default='https://docs.google.com/uc?export=download&id=[ID HERE]')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AudioSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audios', models.ManyToManyField(blank=True, related_name='audio_sets', to='imaginarion.Audio')),
                ('main_audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imaginarion.audio')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=rpg_project.utils.ReplaceFileStorage(), upload_to='post_pics')),
                ('type', models.CharField(choices=[('knowledge', 'KNOWLEDGE'), ('npc', 'NPC'), ('players-notes', 'PLAYERS-NOTES'), ('realia', 'REALIA'), ('symbola', 'SYMBOLA'), ('thera', 'THERA'), ('topoi', 'TOPOI'), ('varia', 'VARIA')], max_length=20)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['type', 'title', 'description'],
            },
        ),
    ]
