# Generated by Django 2.2.1 on 2020-03-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_pics')),
                ('type', models.CharField(choices=[('knowledge', 'KNOWLEDGE'), ('npc', 'NPC'), ('realia', 'REALIA'), ('symbola', 'SYMBOLA'), ('thera', 'THERA'), ('topoi', 'TOPOI'), ('varia', 'VARIA')], max_length=10)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['type', 'title', 'description'],
            },
        ),
    ]
