# Generated by Django 4.0.2 on 2022-03-25 10:27

from django.db import migrations, models
import django.db.models.deletion
import rpg_project.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('domeny', 'DOMENY'), ('npc', 'NPC'), ('topoi', 'TOPOI'), ('varia', 'VARIA')], max_length=10)),
                ('path', models.TextField(default='https://docs.google.com/uc?export=download&id=[ID HERE]')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AudioSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audios', models.ManyToManyField(blank=True, related_name='audio_sets', to='imaginarion.Audio')),
                ('main_audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imaginarion.audio')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PictureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=rpg_project.utils.ReplaceFileStorage(), upload_to='post_pics')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('knowledge', 'KNOWLEDGE'), ('npc', 'NPC'), ('players-notes', 'PLAYERS-NOTES'), ('profile', 'PROFILE'), ('realia', 'REALIA'), ('symbola', 'SYMBOLA'), ('thera', 'THERA'), ('topoi', 'TOPOI'), ('varia', 'VARIA')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_pics', to='imaginarion.pictureimage')),
            ],
            options={
                'ordering': ['type', 'sorting_name'],
            },
        ),
        migrations.CreateModel(
            name='PictureSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pictures', models.ManyToManyField(blank=True, related_name='picture_sets', to='imaginarion.Picture')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
