# Generated by Django 3.1 on 2021-01-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='type',
            field=models.CharField(choices=[('knowledge', 'KNOWLEDGE'), ('npc', 'NPC'), ('players-notes', 'PLAYERS-NOTES'), ('profile', 'PROFILE'), ('realia', 'REALIA'), ('symbola', 'SYMBOLA'), ('thera', 'THERA'), ('topoi', 'TOPOI'), ('varia', 'VARIA')], max_length=20),
        ),
    ]
