# Generated by Django 3.1 on 2020-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0002_auto_20200405_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NPC', 'Npc'), ('TOPOI', 'Topoi'), ('VARIA', 'Varia')], max_length=5)),
                ('path', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('info', models.TextField(blank=True, max_length=500, null=True, unique=True)),
            ],
            options={
                'ordering': ['type', 'title'],
            },
        ),
    ]
