# Generated by Django 4.0.4 on 2022-05-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0002_alter_picture_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['type', 'image']},
        ),
        migrations.AlterModelOptions(
            name='pictureimage',
            options={'ordering': ['image']},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='pictureimage',
            name='sorting_name',
        ),
    ]
