# Generated by Django 3.1 on 2020-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0003_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
