# Generated by Django 3.1 on 2021-02-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0003_auto_20210121_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['type', 'sorting_name']},
        ),
        migrations.AddField(
            model_name='picture',
            name='sorting_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
