# Generated by Django 3.1 on 2021-02-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0004_auto_20210220_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='title',
        ),
    ]
