# Generated by Django 3.1 on 2020-09-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0004_auto_20200915_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='type',
            field=models.CharField(choices=[('npc', 'NPC'), ('topoi', 'TOPOI'), ('varia', 'VARIA')], max_length=5),
        ),
    ]
