# Generated by Django 3.1 on 2020-11-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0005_auto_20200915_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audios', models.ManyToManyField(blank=True, related_name='audio_sets', to='imaginarion.Audio')),
                ('main_audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imaginarion.audio')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
