# Generated by Django 3.1 on 2021-02-20 12:53

from django.db import migrations, models
import django.db.models.deletion
import rpg_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0005_remove_picture_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=rpg_project.utils.ReplaceFileStorage(), upload_to='post_pics')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
        migrations.AddField(
            model_name='picture',
            name='image_replacement_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imaginarion.pictureimage'),
        ),
    ]
