# Generated by Django 3.1 on 2020-11-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0006_audioset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='info',
        ),
        migrations.AddField(
            model_name='audio',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='audioset',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
