# Generated by Django 3.1 on 2021-02-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0006_auto_20210220_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='image_old',
        ),
    ]
