# Generated by Django 3.1 on 2020-11-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0007_auto_20201104_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.TextField(default='https://docs.google.com/uc?export=download&id=[REPLACE WITH ID]'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
