# Generated by Django 3.1 on 2021-02-20 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0007_auto_20210220_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image_replacement_field',
            new_name='image',
        ),
    ]
