# Generated by Django 3.1 on 2021-02-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0009_auto_20210220_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='image_old',
        ),
    ]
