# Generated by Django 3.1 on 2020-11-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0009_auto_20201108_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='type',
            field=models.CharField(choices=[('knowledge', 'KNOWLEDGE'), ('npc', 'NPC'), ('players-notes', 'PLAYERS-NOTES'), ('realia', 'REALIA'), ('symbola', 'SYMBOLA'), ('thera', 'THERA'), ('topoi', 'TOPOI'), ('varia', 'VARIA')], max_length=20),
        ),
    ]
