# Generated by Django 3.1 on 2021-02-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0010_remove_picture_image_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_pics', to='imaginarion.pictureimage'),
        ),
    ]
