# Generated by Django 3.1 on 2020-11-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0010_auto_20201108_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.TextField(default='https://docs.google.com/uc?export=download&id=[ID HERE]'),
        ),
    ]
