# Generated by Django 3.1 on 2020-09-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toponomikon', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_storages', to='toponomikon.secondarylocation')),
                ('owners', models.ManyToManyField(related_name='item_storages', to='users.Profile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='equipment.itemstorage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
