# Generated by Django 2.2.1 on 2019-07-11 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('forum', '0001_initial'), ('forum', '0002_auto_20190625_1739'), ('forum', '0003_auto_20190627_1508'), ('forum', '0004_auto_20190627_1641'), ('forum', '0005_auto_20190627_1754'), ('forum', '0006_auto_20190628_1244'), ('forum', '0007_auto_20190628_1245'), ('forum', '0008_topic_allowed_profiles'), ('forum', '0009_auto_20190628_1510'), ('forum', '0010_auto_20190703_1440'), ('forum', '0011_post_image'), ('forum', '0012_auto_20190703_1635'), ('forum', '0013_auto_20190703_1636'), ('forum', '0014_auto_20190703_1707'), ('forum', '0015_post_text_editor'), ('forum', '0016_remove_post_text_editor'), ('forum', '0017_auto_20190705_1907'), ('forum', '0018_auto_20190706_1158'), ('forum', '0019_remove_topic_allowed_users'), ('forum', '0020_auto_20190710_1733'), ('forum', '0021_auto_20190710_1733'), ('forum', '0022_auto_20190710_1749'), ('forum', '0023_auto_20190710_1749'), ('forum', '0024_auto_20190710_1750'), ('forum', '0025_auto_20190710_1752')]

    initial = True

    dependencies = [
        ('users', '0004_auto_20190628_1245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.Board')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
                ('allowed_profiles', models.ManyToManyField(limit_choices_to=models.Q(('character_status', 'player'), ('character_status', 'npc'), _connector='OR'), related_name='allowed_topics', to='users.Profile')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='forum.Topic')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_pics')),
            ],
        ),
    ]
