# Generated by Django 2.2.1 on 2019-07-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_squashed_0025_auto_20190710_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
