# Generated by Django 2.2.1 on 2019-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190712_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='allowed_profiles',
            field=models.ManyToManyField(limit_choices_to=models.Q(('character_status', 'active_player'), ('character_status', 'inactive_player'), ('character_status', 'living_npc'), _connector='OR'), related_name='allowed_topics', to='users.Profile'),
        ),
    ]
