# Generated by Django 2.2.1 on 2019-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_topic_is_individual'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
    ]
