# Generated by Django 4.0.2 on 2022-03-25 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [('contact', '0001_initial'), ('contact', '0002_auto_20201226_2252'), ('contact', '0003_auto_20201228_2101'), ('contact', '0004_auto_20210106_1733'), ('contact', '0005_auto_20210106_1743'), ('contact', '0006_auto_20210106_1752'), ('contact', '0007_auto_20210205_0001'), ('contact', '0008_auto_20211017_1835')]

    initial = True

    dependencies = [
        ('users', '0001_initial_squashed'),
        # ('users', '0009_auto_20210912_1017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_pics')),
                ('is_done', models.BooleanField(default=False)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_demands', to='users.profile')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authored_demands', to='users.profile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DemandAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_pics')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_answers', to='contact.demand')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demand_answers', to='users.profile')),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform_gm', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_pics')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='users.profile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
