# Generated by Django 2.2.1 on 2020-03-25 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_pics')),
                ('is_done', models.BooleanField(default=False)),
                ('addressee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_demands', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_demands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inform_gm', models.BooleanField(default=False)),
                ('text', models.TextField(max_length=4000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DemandAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contact_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_answers', to=settings.AUTH_USER_MODEL)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_answers', to='contact.Demand')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
