# Generated by Django 2.2.1 on 2020-04-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandanswer',
            options={'ordering': ['date_posted']},
        ),
    ]
