# Generated by Django 3.1 on 2020-12-26 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_demands', to=settings.AUTH_USER_MODEL, verbose_name='Adresat'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz [opcjonalnie]:'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='text',
            field=models.TextField(verbose_name='Treść'),
        ),
        migrations.AlterField(
            model_name='demandanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz [opcjonalnie]:'),
        ),
        migrations.AlterField(
            model_name='demandanswer',
            name='text',
            field=models.TextField(verbose_name='Odpowiedź'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz [opcjonalnie]:'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='inform_gm',
            field=models.BooleanField(default=False, verbose_name='Poinformuj MG'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='text',
            field=models.TextField(verbose_name='Treść'),
        ),
    ]
