# Generated by Django 4.0.2 on 2022-03-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_user_image'),
        ('contact', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_demands', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='demandanswer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_answers', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='users.profile'),
        ),
    ]
