# Generated by Django 2.2.1 on 2020-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200404_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='text',
            field=models.TextField(),
        ),
    ]
