# Generated by Django 3.1 on 2020-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20201226_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz [opcjonalnie]'),
        ),
        migrations.AlterField(
            model_name='demandanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz [opcjonalnie]'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz [opcjonalnie]'),
        ),
    ]
