# Generated by Django 2.2.1 on 2020-08-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200731_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandanswer',
            name='text',
            field=models.TextField(),
        ),
    ]
