# Generated by Django 3.1 on 2021-01-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20210106_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='addressee',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='author',
        ),
        migrations.RemoveField(
            model_name='demandanswer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='author',
        ),
    ]
