# Generated by Django 3.1 on 2021-01-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20210106_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demand',
            old_name='addressee2',
            new_name='addressee',
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='author2',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='demandanswer',
            old_name='author2',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='author2',
            new_name='author',
        ),
    ]
