# Generated by Django 3.1 on 2021-02-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20210106_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz'),
        ),
        migrations.AlterField(
            model_name='demandanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics', verbose_name='Obraz'),
        ),
    ]
