# Generated by Django 3.1 on 2021-10-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210912_1017'),
        ('contact', '0007_auto_20210205_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='addressee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_demands', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='demandanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics'),
        ),
        migrations.AlterField(
            model_name='demandanswer',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pics'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='inform_gm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='text',
            field=models.TextField(),
        ),
    ]
