# Generated by Django 3.1 on 2021-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210106_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-status', '-is_active', 'user__username']},
        ),
        migrations.AddField(
            model_name='profile',
            name='copied_character_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('gm', 'MG'), ('npc', 'BN'), ('player', 'GRACZ')], default='npc', max_length=50),
        ),
    ]
