# Generated by Django 3.1 on 2021-03-09 18:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210106_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pics/profile_default.jpg', null=True, storage=users.models.ReplaceFileStorage(), upload_to='profile_pics'),
        ),
    ]
