# Generated by Django 3.1 on 2021-10-23 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_user_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='copied_character_name',
            new_name='character_name_copy',
        ),
    ]
