# Generated by Django 3.1 on 2021-10-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211023_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-status', '-is_active', 'user__username']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_fk',
            new_name='user',
        ),
    ]
