# Generated by Django 3.2.8 on 2022-01-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211023_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-status', '-is_active', 'character_name_copy']},
        ),
    ]
