# Generated by Django 4.0.2 on 2022-03-26 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imaginarion', '0001_initial_squashed'),
        ('users', '0001_initial_squashed'),
        ('knowledge', '0001_initial_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_img', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_types', to='imaginarion.picture')),
                ('name_plural', models.CharField(blank=True, max_length=100, null=True)),
                ('order_no', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['order_no'],
                'verbose_name': '* LOCATION TYPE',
                'verbose_name_plural': '* LOCATION TYPES',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('in_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='toponomikon.location')),
                ('knowledge_packets', models.ManyToManyField(blank=True, related_name='locations', to='knowledge.KnowledgePacket')),
                ('participants', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='locations_participated', to='users.Profile')),
                ('informees', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='locations_informed', to='users.Profile')),
                ('location_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='toponomikon.locationtype')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_main_pics', to='imaginarion.picture')),
                ('map_packets', models.ManyToManyField(blank=True, related_name='locations', to='knowledge.MapPacket')),
                ('audio_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='imaginarion.audioset')),
                ('picture_sets', models.ManyToManyField(blank=True, related_name='locations', to='imaginarion.PictureSet')),
            ],
            options={
                'ordering': ['sorting_name'],
                'verbose_name': '* LOCATION',
                'verbose_name_plural': '* LOCATIONS',
            },
        ),
        migrations.CreateModel(
            name='MainLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toponomikon.location',),
        ),
        migrations.DeleteModel(
            name='MainLocation',
        ),
        migrations.CreateModel(
            name='PrimaryLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
                'verbose_name': '--- Primary Location',
                'verbose_name_plural': '--- Primary Locations',
            },
            bases=('toponomikon.location',),
        ),
        migrations.CreateModel(
            name='SecondaryLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
                'verbose_name': '--- Secondary Location',
                'verbose_name_plural': '--- Secondary Locations',
            },
            bases=('toponomikon.location',),
        ),
        migrations.CreateModel(
            name='TertiaryLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toponomikon.location',),
        ),
        migrations.DeleteModel(
            name='TertiaryLocation',
        ),
    ]
