# Generated by Django 3.1 on 2021-01-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['sorting_name'], 'verbose_name': '* LOCATION', 'verbose_name_plural': '* LOCATIONS'},
        ),
        migrations.AlterModelOptions(
            name='locationtype',
            options={'ordering': ['order_no'], 'verbose_name': '* LOCATION TYPE', 'verbose_name_plural': '* LOCATION TYPES'},
        ),
        migrations.AlterModelOptions(
            name='primarylocation',
            options={'verbose_name': '--- Primary Location', 'verbose_name_plural': '--- Primary Locations'},
        ),
        migrations.AlterModelOptions(
            name='secondarylocation',
            options={'verbose_name': '--- Secondary Location', 'verbose_name_plural': '--- Secondary Locations'},
        ),
    ]
