# Generated by Django 2.2.1 on 2020-06-20 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_auto_20200419_1413'),
        ('users', '0001_initial'),
        ('imaginarion', '0001_initial'),
        ('toponomikon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('in_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='toponomikon.Location')),
                ('knowledge_packets', models.ManyToManyField(blank=True, related_name='locations', to='knowledge.KnowledgePacket')),
                ('known_directly', models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='locations_known_directly', to='users.Profile')),
                ('known_indirectly', models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='locations_known_indirectly', to='users.Profile')),
                ('location_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='toponomikon.LocationType')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations_main_pics', to='imaginarion.Picture')),
                ('pictures', models.ManyToManyField(blank=True, related_name='locations_pics', to='imaginarion.Picture')),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
    ]
