# Generated by Django 4.0.4 on 2022-05-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': '--- LOCATIONS'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='sorting_name',
        ),
    ]
