# Generated by Django 4.0.2 on 2022-03-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0001_0001_initial_squashed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='known_directly',
            new_name='witnesses',
        ),
    ]
