# Generated by Django 4.0.4 on 2022-08-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
