# Generated by Django 3.1 on 2021-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210106_1613'),
        ('toponomikon', '0002_auto_20210103_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='known_directly',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='locs_known_directly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='known_indirectly',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='locs_known_indirectly', to='users.Profile'),
        ),
    ]
