# Generated by Django 4.0.4 on 2022-08-26 14:55

from django.db import migrations
import rpg_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0002_alter_locationtype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')], 'verbose_name': 'Location', 'verbose_name_plural': '--- LOCATIONS'},
        ),
    ]
