# Generated by Django 4.0.2 on 2022-03-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('toponomikon', '0002_rename_known_directly_location_witnesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='witnesses',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='locations_witnessed', to='users.Profile'),
        ),
    ]
