# Generated by Django 4.0.2 on 2022-03-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0003_alter_location_witnesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='witnesses',
            new_name='participants',
        ),
    ]
