# Generated by Django 2.2.1 on 2020-06-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0003_auto_20200620_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='in_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='toponomikon.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations_main_pics', to='imaginarion.Picture'),
        ),
    ]
