# Generated by Django 3.1 on 2021-09-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0012_pictureset'),
        ('toponomikon', '0003_auto_20210106_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='pictures',
        ),
        migrations.AddField(
            model_name='location',
            name='picture_sets',
            field=models.ManyToManyField(blank=True, related_name='locations', to='imaginarion.PictureSet'),
        ),
    ]
