# Generated by Django 4.0.2 on 2022-03-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('toponomikon', '0004_rename_witnesses_location_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='locations_participated', to='users.Profile'),
        ),
    ]
