# Generated by Django 4.0.2 on 2022-03-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0005_alter_location_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='known_indirectly',
            new_name='informees',
        ),
    ]
