# Generated by Django 2.2.1 on 2020-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0006_auto_20200620_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='known_directly',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='locs_known_directly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='location',
            name='known_indirectly',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='locs_known_indirectly', to='users.Profile'),
        ),
    ]
