# Generated by Django 2.2.1 on 2020-06-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20200621_1443'),
        ('toponomikon', '0007_auto_20200621_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificlocation',
            name='general_location',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='knowledge_packets',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='known_directly',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='known_indirectly',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='specificlocation',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='location',
            name='in_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='toponomikon.Location'),
        ),
        migrations.DeleteModel(
            name='GeneralLocation',
        ),
        migrations.DeleteModel(
            name='SpecificLocation',
        ),
    ]
