# Generated by Django 2.2.1 on 2020-06-21 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0008_auto_20200621_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtype',
            name='name_plural',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locationtype',
            name='order_no',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
