# Generated by Django 2.2.1 on 2020-06-21 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0009_auto_20200621_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtype',
            name='order_no',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
