# Generated by Django 2.2.1 on 2020-06-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0010_auto_20200621_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationtype',
            options={'ordering': ['order_no']},
        ),
    ]
