# Generated by Django 2.2.1 on 2020-06-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0011_auto_20200623_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toponomikon.location',),
        ),
    ]
