# Generated by Django 2.2.1 on 2020-06-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0012_mainlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainLocation',
        ),
        migrations.CreateModel(
            name='PrimaryLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toponomikon.location',),
        ),
    ]
