# Generated by Django 2.2.1 on 2020-06-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0013_auto_20200627_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toponomikon.location',),
        ),
    ]
