# Generated by Django 2.2.1 on 2020-07-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0015_auto_20200627_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='TertiaryLocation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('toponomikon.location',),
        ),
    ]
