# Generated by Django 2.2.1 on 2020-07-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0016_tertiarylocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TertiaryLocation',
        ),
    ]
