# Generated by Django 3.1 on 2020-09-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0018_auto_20200708_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='audio_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
