# Generated by Django 3.1 on 2020-09-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0019_location_audio_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='audio_path',
        ),
    ]
