# Generated by Django 3.1 on 2020-09-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0001_initial'),
        ('toponomikon', '0020_remove_location_audio_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='audio_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='imaginarion.audio'),
        ),
    ]
