# Generated by Django 3.1 on 2020-09-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0021_location_audio_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='audio_path',
            new_name='audio',
        ),
    ]
