# Generated by Django 3.1 on 2020-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_mappacket'),
        ('toponomikon', '0022_auto_20200915_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='maps_packets',
            field=models.ManyToManyField(blank=True, related_name='locations', to='knowledge.MapPacket'),
        ),
    ]
