# Generated by Django 3.1 on 2020-10-31 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0023_location_maps_packets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='maps_packets',
            new_name='map_packets',
        ),
    ]
