# Generated by Django 3.1 on 2020-11-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0001_initial'),
        ('toponomikon', '0024_auto_20201031_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='audio',
        ),
        migrations.AddField(
            model_name='location',
            name='audio_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='imaginarion.audioset'),
        ),
    ]
