# Generated by Django 4.0.2 on 2022-03-25 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0001_squashed_0069_delete_charactergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='known_directly',
            new_name='witnesses',
        ),
    ]
