# Generated by Django 4.0.4 on 2022-05-19 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': '* CHARACTER', 'verbose_name_plural': '* CHARACTERS'},
        ),
        migrations.RenameField(
            model_name='character',
            old_name='sorting_name',
            new_name='name',
        ),
    ]
