# Generated by Django 4.0.2 on 2022-04-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyname',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='prosoponomikon.familynamegroup'),
            preserve_default=False,
        ),
    ]
