# Generated by Django 4.0.4 on 2022-05-19 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0002_alter_character_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['fullname'], 'verbose_name': '* CHARACTER', 'verbose_name_plural': '* CHARACTERS'},
        ),
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='fullname',
        ),
    ]
