# Generated by Django 4.0.4 on 2022-07-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('prosoponomikon', '0002_acquisition_character_skill_levels_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquisition',
            options={'ordering': ['character', 'skill_level__skill', 'skill_level']},
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='prosoponomikon.character'),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='skill_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisitions', to='rules.skilllevel'),
        ),
    ]
