# Generated by Django 4.0.2 on 2022-03-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('prosoponomikon', '0002_rename_known_directly_character_witnesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='witnesses',
            field=models.ManyToManyField(blank=True, related_name='characters_witnessed', to='users.Profile'),
        ),
    ]
