# Generated by Django 4.0.4 on 2022-07-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('prosoponomikon', '0003_alter_acquisition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAcquisitions',
            fields=[
            ],
            options={
                'verbose_name': '*Character (ACQUISITIONS)',
                'verbose_name_plural': '*Characters (ACQUISITIONS)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.character',),
        ),
        migrations.AlterUniqueTogether(
            name='acquisition',
            unique_together={('character', 'skill_level', 'sphragis'), ('character', 'skill_level', 'weapon')},
        ),
    ]
