# Generated by Django 4.0.4 on 2022-05-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
        ('prosoponomikon', '0004_alter_character_cognomen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='professions',
        ),
        migrations.AddField(
            model_name='character',
            name='subprofessions',
            field=models.ManyToManyField(blank=True, related_name='characters', to='rules.subprofession'),
        ),
    ]
