# Generated by Django 3.1 on 2020-12-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0004_character_descr_psychophysical'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='descr_for_gm',
            field=models.TextField(blank=True, null=True),
        ),
    ]
