# Generated by Django 4.0.4 on 2022-06-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0005_remove_character_professions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='fullname',
            field=models.CharField(max_length=150),
        ),
    ]
