# Generated by Django 4.0.4 on 2022-06-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0006_alter_character_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acquaintanceship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_direct', models.BooleanField()),
                ('knows_if_dead', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='acquaintances',
            field=models.ManyToManyField(blank=True, related_name='acquaintaned_to', through='prosoponomikon.Acquaintanceship', to='prosoponomikon.character'),
        ),
        migrations.AddField(
            model_name='acquaintanceship',
            name='knowing_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='known_characters', to='prosoponomikon.character'),
        ),
        migrations.AddField(
            model_name='acquaintanceship',
            name='known_character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowing_characters', to='prosoponomikon.character'),
        ),
    ]
