# Generated by Django 4.0.2 on 2022-03-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('prosoponomikon', '0006_rename_known_indirectly_character_informees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='informees',
            field=models.ManyToManyField(blank=True, related_name='characters_informed', to='users.Profile'),
        ),
    ]
