# Generated by Django 3.1 on 2020-12-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201225_1757'),
        ('knowledge', '0002_auto_20201225_1400'),
        ('prosoponomikon', '0006_auto_20201225_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charactergroup',
            name='knowledge_packets',
        ),
        migrations.AddField(
            model_name='charactergroup',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_groups_authored', to='users.profile'),
        ),
        migrations.AddField(
            model_name='charactergroup',
            name='default_knowledge_packets',
            field=models.ManyToManyField(blank=True, related_name='character_group_defaults', to='knowledge.KnowledgePacket'),
        ),
        migrations.AddField(
            model_name='charactergroup',
            name='order_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
