# Generated by Django 4.0.4 on 2022-08-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('prosoponomikon', '0006_alter_acquaintanceship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters_created', to='users.profile'),
        ),
    ]
