# Generated by Django 4.0.4 on 2022-06-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0007_acquaintanceship_character_acquaintances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquaintanceship',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acquaintanceship',
            name='knows_if_dead',
            field=models.BooleanField(default=False),
        ),
    ]
