# Generated by Django 3.1 on 2020-12-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0007_auto_20201226_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charactergroup',
            options={'ordering': ['order_no', 'name']},
        ),
        migrations.RemoveField(
            model_name='character',
            name='character_groups',
        ),
        migrations.AddField(
            model_name='charactergroup',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='character_groups', to='prosoponomikon.Character'),
        ),
    ]
