# Generated by Django 4.0.2 on 2022-03-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0007_alter_character_informees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NameGroup',
            new_name='FirstNameGroup',
        ),
    ]
