# Generated by Django 4.0.4 on 2022-06-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0008_alter_acquaintanceship_is_direct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acquaintanceship',
            options={'ordering': ['known_character']},
        ),
        migrations.AlterUniqueTogether(
            name='acquaintanceship',
            unique_together={('known_character', 'knowing_character')},
        ),
    ]
