# Generated by Django 4.0.4 on 2022-10-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0008_alter_auxiliarynamegroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquaintanceship',
            name='knows_as_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
