# Generated by Django 4.0.4 on 2022-10-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0009_acquaintanceship_knows_as_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstname',
            name='is_ancient',
        ),
    ]
