# Generated by Django 4.0.4 on 2022-10-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0010_remove_firstname_is_ancient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquaintanceship',
            name='knows_as_image',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics'),
            preserve_default=False,
        ),
    ]
