# Generated by Django 4.0.4 on 2022-07-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0010_remove_character_informees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='endurance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
