# Generated by Django 4.0.4 on 2022-07-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0011_character_dexterity_character_endurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
