# Generated by Django 4.0.4 on 2022-11-27 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0011_alter_acquaintanceship_knows_as_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquaintanceshipProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.acquaintanceship',),
        ),
    ]
