# Generated by Django 3.1 on 2021-01-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0001_initial'),
        ('prosoponomikon', '0012_auto_20210103_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='description_main',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='visited_locations',
        ),
        migrations.AddField(
            model_name='persona',
            name='frequented_locations',
            field=models.ManyToManyField(blank=True, related_name='frequented_by_personas', to='toponomikon.Location'),
        ),
        migrations.AlterField(
            model_name='personagroup',
            name='order_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Numer porządkowy grupy [opcjonalnie]'),
        ),
    ]
