# Generated by Django 4.0.4 on 2022-12-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_rename_weapon_skill_weapon_type'),
        ('prosoponomikon', '0012_acquaintanceshipproxy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acquisition',
            old_name='weapon',
            new_name='weapon_type',
        ),
        migrations.AlterUniqueTogether(
            name='acquisition',
            unique_together={('character', 'skill_level', 'weapon_type'), ('character', 'skill_level', 'sphragis')},
        ),
    ]
