# Generated by Django 4.0.4 on 2022-07-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0012_character_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAcquaintanceships',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Character Acquaintanceships',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.character',),
        ),
    ]
