# Generated by Django 4.0.4 on 2022-07-08 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0013_characteracquaintanceships'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['fullname'], 'verbose_name': '*Character', 'verbose_name_plural': '*Characters (ALL)'},
        ),
        migrations.AlterModelOptions(
            name='characteracquaintanceships',
            options={'verbose_name': '*Character (ACQUAINTANCESHIPS)', 'verbose_name_plural': '*Characters (ACQUAINTANCESHIPS)'},
        ),
        migrations.AlterModelOptions(
            name='npccharacter',
            options={'verbose_name': '- NPC', 'verbose_name_plural': '- NPCs'},
        ),
        migrations.AlterModelOptions(
            name='playercharacter',
            options={'verbose_name': '- Player', 'verbose_name_plural': '- Players'},
        ),
    ]
