# Generated by Django 4.1.7 on 2023-03-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0013_rename_weapon_acquisition_weapon_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstname',
            name='comments',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='firstname',
            name='equivalents',
            field=models.ManyToManyField(blank=True, to='prosoponomikon.firstname'),
        ),
        migrations.AddField(
            model_name='firstname',
            name='isarchaic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firstname',
            name='meaning',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='firstname',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originatedfirstnames', to='prosoponomikon.firstname'),
        ),
    ]
