# Generated by Django 3.1 on 2021-01-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0013_auto_20210103_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nonplayerpersona',
            options={'verbose_name': '--- NPC', 'verbose_name_plural': '--- NPCs'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['sorting_name'], 'verbose_name': '* PERSONAS', 'verbose_name_plural': '* PERSONAS'},
        ),
        migrations.AlterModelOptions(
            name='personagroup',
            options={'ordering': ['order_no', 'name'], 'verbose_name': '* PERSONA GROUP', 'verbose_name_plural': '* PERSONA GROUPS'},
        ),
        migrations.AlterModelOptions(
            name='playerpersona',
            options={'verbose_name': '--- Player', 'verbose_name_plural': '--- Players'},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='picture_main',
        ),
    ]
