# Generated by Django 4.1.7 on 2023-03-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0014_firstname_comments_firstname_equivalents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstname',
            name='form_2',
        ),
        migrations.RemoveField(
            model_name='firstname',
            name='info',
        ),
    ]
