# Generated by Django 4.1.7 on 2023-05-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0015_remove_firstname_form_2_remove_firstname_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='power',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
