# Generated by Django 3.1 on 2021-01-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_biographypacket_show_in_prosoponomikon'),
        ('prosoponomikon', '0015_auto_20210106_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NonPlayerPersona',
        ),
        migrations.CreateModel(
            name='NPCPersona',
            fields=[
            ],
            options={
                'verbose_name': '--- NPC',
                'verbose_name_plural': '--- NPCs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.persona',),
        ),
        migrations.AlterField(
            model_name='personagroup',
            name='default_knowledge_packets',
            field=models.ManyToManyField(blank=True, related_name='persona_group_defaults', to='knowledge.KnowledgePacket', verbose_name='Domyślne umiejętności NPC w grupie'),
        ),
    ]
