# Generated by Django 4.1.7 on 2023-05-27 16:42

from django.db import migrations, models
import django.db.models.deletion
import rpg_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_sorcererspell_theurgistspell'),
        ('prosoponomikon', '0016_character_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterSpellAcquisitions',
            fields=[
            ],
            options={
                'verbose_name': '*Character (Spell Acquisitions)',
                'verbose_name_plural': '*Characters (Spell Acquisitions)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('prosoponomikon.character',),
        ),
        migrations.CreateModel(
            name='SpellAcquisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spellacquisitions', to='prosoponomikon.character')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spellacquisitions', to='rules.spell')),
                ('sphragis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.domain')),
            ],
            options={
                'ordering': [rpg_project.utils.OrderByPolish('character__fullname'), 'spell__level', rpg_project.utils.OrderByPolish('spell__name')],
                'unique_together': {('character', 'spell', 'sphragis')},
            },
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(blank=True, related_name='acquiring_characters', through='prosoponomikon.SpellAcquisition', to='rules.spell'),
        ),
    ]
