# Generated by Django 4.1.7 on 2023-05-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_sorcererspell_theurgistspell'),
        ('prosoponomikon', '0017_characterspellacquisitions_spellacquisition_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acquisition',
            unique_together={('character', 'skill_level', 'weapon_type')},
        ),
        migrations.RemoveField(
            model_name='acquisition',
            name='sphragis',
        ),
    ]
