# Generated by Django 4.1.7 on 2023-05-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_remove_spell_damage_spell_effect_description'),
        ('prosoponomikon', '0019_spellacquisition_sphere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spellacquisition',
            name='sphere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spellacquisitions', to='rules.sphere'),
        ),
        migrations.AlterField(
            model_name='spellacquisition',
            name='sphragis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spellacquisitions', to='rules.domain'),
        ),
    ]
