# Generated by Django 3.1 on 2021-01-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0021_auto_20210131_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='birth_location',
        ),
        migrations.AlterField(
            model_name='charactergroup',
            name='order_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nr porządkowy'),
        ),
    ]
