# Generated by Django 3.1 on 2021-02-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0023_auto_20210220_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='cognomen',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
