# Generated by Django 3.1 on 2021-02-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0030_auto_20210221_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='nameform',
            name='type',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('daemon', 'DAEMON')], default='male', max_length=20),
        ),
    ]
