# Generated by Django 3.1 on 2021-02-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0031_nameform_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nameform',
            name='name_groups',
            field=models.ManyToManyField(blank=True, related_name='names', to='prosoponomikon.NameGroup'),
        ),
    ]
