# Generated by Django 3.1 on 2021-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0032_auto_20210221_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameform',
            name='name_groups',
            field=models.ManyToManyField(blank=True, related_name='names', to='prosoponomikon.NameGroup'),
        ),
    ]
