# Generated by Django 3.1 on 2021-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0035_auto_20210225_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nameform',
            name='type',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('DAEMON', 'DAEMON')], default='male', max_length=20),
        ),
    ]
