# Generated by Django 3.1 on 2021-03-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0042_auto_20210305_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affixgroup',
            options={'ordering': ['name_group', 'affix']},
        ),
        migrations.AlterField(
            model_name='affixgroup',
            name='name_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affix_groups', to='prosoponomikon.namegroup'),
        ),
        migrations.AlterField(
            model_name='auxiliarynamegroup',
            name='social_info',
            field=models.TextField(blank=True, help_text='Social group indication if no location', null=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='affix_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='names', to='prosoponomikon.affixgroup'),
        ),
    ]
