# Generated by Django 3.1 on 2021-03-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0046_auto_20210308_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
