# Generated by Django 3.1 on 2021-03-10 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0047_auto_20210310_1828'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='FirstName',
        ),
    ]
