# Generated by Django 3.1 on 2021-03-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0049_auto_20210310_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='first_name',
        ),
    ]
