# Generated by Django 3.1 on 2021-03-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0050_auto_20210310_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstname',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstname',
            name='affix_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='first_names', to='prosoponomikon.affixgroup'),
        ),
    ]
