# Generated by Django 3.1 on 2021-03-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0051_auto_20210310_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstname',
            options={'ordering': ['auxiliary_group', 'form']},
        ),
    ]
