# Generated by Django 3.1 on 2021-03-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0052_auto_20210311_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliarynamegroup',
            options={'ordering': ['social_info', 'location']},
        ),
    ]
