# Generated by Django 3.1 on 2021-03-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0056_firstname_form_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='namegroup',
            name='type',
            field=models.CharField(choices=[('local', 'local'), ('social', 'social')], default='local', max_length=50),
            preserve_default=False,
        ),
    ]
