# Generated by Django 3.1 on 2021-03-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0059_auto_20210320_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyname',
            name='auxiliary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prosoponomikon.auxiliarynamegroup'),
        ),
    ]
