# Generated by Django 3.1 on 2021-03-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0061_remove_familyname_auxiliary_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyNameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='familyname',
            options={'ordering': ['group', 'form']},
        ),
        migrations.AddField(
            model_name='familyname',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prosoponomikon.familynamegroup'),
        ),
    ]
