# Generated by Django 3.1 on 2021-09-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0065_auto_20210807_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='pictures',
        ),
    ]
