# Generated by Django 4.0.2 on 2022-03-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0059_alter_conditionalmodifier_options'),
        ('prosoponomikon', '0067_auto_20211017_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='professions',
            field=models.ManyToManyField(blank=True, related_name='characters', to='rules.Profession'),
        ),
    ]
