# Generated by Django 3.1 on 2021-01-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210106_1613'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliteklass',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='allowed_elite_klasses', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='eliteprofession',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='allowed_elite_classes', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='allowed_klasses', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='allowed_plates', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='allowed_shields', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='allowed_skills', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='synergy',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='allowed_synergies', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status='player'), related_name='allowed_weapons', to='users.Profile'),
        ),
    ]
