# Generated by Django 3.1 on 2021-09-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0012_pictureset'),
        ('rules', '0002_auto_20210106_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='picture_sets',
            field=models.ManyToManyField(blank=True, related_name='plates', to='imaginarion.PictureSet'),
        ),
        migrations.AddField(
            model_name='shield',
            name='picture_sets',
            field=models.ManyToManyField(blank=True, related_name='shields', to='imaginarion.PictureSet'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='picture_sets',
            field=models.ManyToManyField(blank=True, related_name='weapons', to='imaginarion.PictureSet'),
        ),
    ]
