# Generated by Django 3.1 on 2020-09-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_auto_20200926_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterprofession',
            old_name='character_class',
            new_name='profession',
        ),
    ]
