# Generated by Django 3.1 on 2020-09-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_auto_20200926_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eliteklass',
            options={'ordering': ['sorting_name'], 'verbose_name': 'Elite klass', 'verbose_name_plural': 'Elite klasses'},
        ),
        migrations.AlterModelOptions(
            name='eliteprofession',
            options={'ordering': ['sorting_name'], 'verbose_name': 'Elite profession', 'verbose_name_plural': 'Elite professions'},
        ),
    ]
