# Generated by Django 3.1 on 2020-11-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('rules', '0017_auto_20200926_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliteklass',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='allowed_elite_klasses', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='eliteprofession',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='allowed_elite_classes', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='allowed_klasses', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='allowed_plates', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='allowed_shields', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='allowed_skills', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='synergy',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='allowed_synergies', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(status__in=['active_player', 'inactive_player', 'dead_player']), related_name='allowed_weapons', to='users.Profile'),
        ),
    ]
