# Generated by Django 2.2.1 on 2019-07-12 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190712_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('season', models.CharField(choices=[('1', 'Wiosna'), ('2', 'Lato'), ('3', 'Jesień'), ('4', 'Zima')], max_length=100)),
                ('day_start', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('day_end', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)])),
                ('description', models.TextField(max_length=4000)),
                ('informed', models.ManyToManyField(blank=True, limit_choices_to={'status': 'player'}, related_name='events_informed', to='users.Profile')),
                ('participants', models.ManyToManyField(blank=True, limit_choices_to={'status': 'player'}, related_name='events_participated', to='users.Profile')),
            ],
        ),
    ]
