# Generated by Django 2.2.1 on 2020-04-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineeventnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='timelineeventnote',
            name='event',
        ),
        migrations.DeleteModel(
            name='ChronicleEventNote',
        ),
        migrations.DeleteModel(
            name='TimelineEventNote',
        ),
    ]
