# Generated by Django 2.2.1 on 2019-07-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.GeneralLocation')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='general_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='history.GeneralLocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='specific_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='history.SpecificLocation'),
            preserve_default=False,
        ),
    ]
