# Generated by Django 2.2.1 on 2020-06-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20200419_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['game', 'year', 'season', 'day_start', 'day_end', 'description']},
        ),
    ]
