# Generated by Django 2.2.1 on 2019-07-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190713_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('game_no', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['year', 'season', 'day_start', 'day_end', 'game_no']},
        ),
        migrations.AddField(
            model_name='event',
            name='game_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='history.GameSession'),
        ),
        migrations.AddField(
            model_name='event',
            name='thread',
            field=models.ManyToManyField(blank=True, related_name='events', to='history.Thread'),
        ),
    ]
