# Generated by Django 2.2.1 on 2020-06-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0006_auto_20200620_1835'),
        ('history', '0003_auto_20200620_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='places',
            field=models.ManyToManyField(related_name='timeline_events', to='toponomikon.Location'),
        ),
    ]
