# Generated by Django 2.2.1 on 2020-06-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_timelineevent_places'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timelineevent',
            old_name='places',
            new_name='locations',
        ),
    ]
