# Generated by Django 2.2.1 on 2020-06-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0006_auto_20200620_1835'),
        ('history', '0005_auto_20200621_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='locations',
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='gen_locations',
            field=models.ManyToManyField(related_name='timeline_events_in_gen', to='toponomikon.Location'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='spec_locations',
            field=models.ManyToManyField(related_name='timeline_events_in_spec', to='toponomikon.Location'),
        ),
    ]
