# Generated by Django 2.2.1 on 2019-07-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20190713_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='specific_location',
        ),
        migrations.AddField(
            model_name='event',
            name='specific_location',
            field=models.ManyToManyField(related_name='events', to='history.SpecificLocation'),
        ),
    ]
