# Generated by Django 2.2.1 on 2020-06-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20200621_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineevent',
            name='general_locations',
        ),
        migrations.RemoveField(
            model_name='timelineevent',
            name='specific_locations',
        ),
    ]
