# Generated by Django 2.2.1 on 2019-07-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_auto_20190713_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['year', 'season', 'day_start', 'day_end', 'id', 'game_no']},
        ),
    ]
