# Generated by Django 2.2.1 on 2019-07-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20190713_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generallocation',
            options={'ordering': ['name']},
        ),
    ]
