# Generated by Django 2.2.1 on 2019-07-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20190713_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
