# Generated by Django 2.2.1 on 2019-07-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_auto_20190713_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['game_no']},
        ),
    ]
