# Generated by Django 2.2.1 on 2019-07-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_auto_20190713_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['name']},
        ),
    ]
