# Generated by Django 2.2.1 on 2019-07-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0014_auto_20190713_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generallocation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['name']},
        ),
    ]
