# Generated by Django 2.2.1 on 2019-07-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0015_auto_20190713_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='describedevent',
            options={'ordering': ['game_no']},
        ),
        migrations.AlterModelOptions(
            name='generallocation',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='describedevent',
            old_name='text',
            new_name='description',
        ),
    ]
