# Generated by Django 2.2.1 on 2019-07-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0016_auto_20190714_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='thread',
            new_name='threads',
        ),
    ]
