# Generated by Django 2.2.1 on 2019-07-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0017_auto_20190715_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='specific_location',
            new_name='specific_locations',
        ),
    ]
