# Generated by Django 2.2.1 on 2019-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0018_auto_20190715_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generallocation',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='specificlocation',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
