# Generated by Django 2.2.1 on 2019-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0020_auto_20190715_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='season',
            field=models.CharField(choices=[('1', 'Wiosna'), ('2', 'Lato'), ('3', 'Jesień'), ('4', 'Zima')], max_length=10),
        ),
    ]
