# Generated by Django 2.2.1 on 2019-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0021_auto_20190717_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='season',
            field=models.TextField(choices=[('1', 'Wiosna'), ('2', 'Lato'), ('3', 'Jesień'), ('4', 'Zima')], max_length=10),
        ),
    ]
