# Generated by Django 2.2.1 on 2019-07-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190716_1906'),
        ('history', '0023_auto_20190717_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_authors', to='users.Profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='history.Event')),
            ],
        ),
    ]
