# Generated by Django 2.2.1 on 2019-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0024_eventannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventannotation',
            name='color',
            field=models.CharField(choices=[('szary', '#808080'), ('czarny', '#000000'), ('czerwony', '#C70039'), ('pomarańczowy', '#FFC300'), ('zielony', '#229954'), ('niebieski', '#2e86c1'), ('granatowy', '#000080'), ('fioletowy', '#800080')], default='szary', max_length=20),
            preserve_default=False,
        ),
    ]
