# Generated by Django 2.2.1 on 2019-07-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0025_eventannotation_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventannotation',
            name='color',
            field=models.CharField(choices=[('#808080', 'szary'), ('#000000', 'czarny'), ('#C70039', 'czerwony'), ('#FFC300', 'pomarańczowy'), ('#229954', 'zielony'), ('#2e86c1', 'niebieski'), ('#000080', 'granatowy'), ('#800080', 'fioletowy')], max_length=20),
        ),
    ]
