# Generated by Django 2.2.1 on 2019-07-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190716_1906'),
        ('history', '0026_auto_20190718_1249'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventAnnotation',
            new_name='EventNote',
        ),
    ]
