# Generated by Django 2.2.1 on 2019-07-18 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0027_auto_20190718_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='eventnote',
            name='color',
            field=models.CharField(choices=[('#000000', 'czarny'), ('#C70039', 'czerwony'), ('#800080', 'fioletowy'), ('#000080', 'granatowy'), ('#2e86c1', 'niebieski'), ('#FFC300', 'pomarańczowy'), ('#808080', 'szary'), ('#229954', 'zielony')], default='#C70039', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventnote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='history.Event'),
        ),
    ]
