# Generated by Django 2.2.1 on 2019-07-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0029_auto_20190718_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnote',
            name='text',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
