# Generated by Django 2.2.1 on 2019-07-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0030_auto_20190718_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='informed',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('character_status', 'active_player'), ('character_status', 'inactive_player'), _connector='OR'), related_name='events_informed', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('character_status', 'active_player'), ('character_status', 'inactive_player'), ('character_status', 'dead_player'), _connector='OR'), related_name='events_participated', to='users.Profile'),
        ),
    ]
