# Generated by Django 2.2.1 on 2019-07-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0032_describedevent_event_no_in_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describedevent',
            name='informed',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('character_status', 'active_player'), ('character_status', 'inactive_player'), ('character_status', 'dead_player'), _connector='OR'), related_name='described_events_informed', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='describedevent',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('character_status', 'active_player'), ('character_status', 'inactive_player'), ('character_status', 'dead_player'), _connector='OR'), related_name='described_events_participated', to='users.Profile'),
        ),
    ]
