# Generated by Django 2.2.1 on 2019-07-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0033_auto_20190724_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='describedevent',
            options={'ordering': ['game_no', 'event_no_in_game']},
        ),
    ]
