# Generated by Django 2.2.1 on 2019-07-25 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('history', '0034_auto_20190724_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnote',
            name='event',
        ),
        migrations.AddField(
            model_name='eventnote',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventnote',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
