# Generated by Django 2.2.1 on 2019-07-25 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0035_auto_20190725_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventnote',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='eventnote',
            name='object_id',
        ),
        migrations.AddField(
            model_name='eventnote',
            name='event',
            field=models.ForeignKey(default=70, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='history.Event'),
            preserve_default=False,
        ),
    ]
