# Generated by Django 2.2.1 on 2019-07-25 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0036_auto_20190725_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventDescribedNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=4000, null=True)),
                ('color', models.CharField(choices=[('#000000', 'czarny'), ('#C70039', 'czerwony'), ('#800080', 'fioletowy'), ('#000080', 'granatowy'), ('#2e86c1', 'niebieski'), ('#FFC300', 'pomarańczowy'), ('#808080', 'szary'), ('#229954', 'zielony')], default='#C70039', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='described_events_notes', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='history.DescribedEvent')),
            ],
        ),
    ]
