# Generated by Django 2.2.1 on 2019-07-25 07:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0037_auto_20190725_0902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventDescribedNote',
            new_name='DescribedEventNote',
        ),
    ]
