# Generated by Django 2.2.1 on 2019-07-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0038_auto_20190725_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_no',
            field=models.DecimalField(decimal_places=2, max_digits=6, primary_key=True, serialize=False),
        ),
    ]
