# Generated by Django 2.2.1 on 2019-07-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0039_auto_20190726_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_no',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
