# Generated by Django 2.2.1 on 2019-07-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0040_auto_20190726_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_no',
            field=models.SmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
