# Generated by Django 2.2.1 on 2019-07-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0042_auto_20190726_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificlocation',
            name='location_main',
        ),
        migrations.AlterField(
            model_name='describedevent',
            name='game_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='described_events', to='history.GameSession'),
        ),
        migrations.AlterField(
            model_name='describedeventnote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='history.DescribedEvent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='game_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='history.GameSession'),
        ),
        migrations.AlterField(
            model_name='event',
            name='general_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.GeneralLocation'),
        ),
        migrations.AlterField(
            model_name='eventnote',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='history.Event'),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='game_no',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
