# Generated by Django 2.2.1 on 2019-07-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0043_auto_20190728_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describedevent',
            name='game_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='described_events', to='history.GameSession'),
        ),
        migrations.AlterField(
            model_name='event',
            name='game_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='history.GameSession'),
        ),
    ]
