# Generated by Django 2.2.1 on 2019-07-28 09:38

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('history', '0044_auto_20190728_1018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameSession',
            new_name='GameSessionToDiscard',
        ),
    ]
