# Generated by Django 2.2.1 on 2019-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0045_auto_20190728_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_no', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['game_no'],
            },
        ),
    ]
