# Generated by Django 2.2.1 on 2019-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0046_gamesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_no',
            field=models.IntegerField(null=True),
        ),
    ]
