# Generated by Django 2.2.1 on 2019-07-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0048_auto_20190728_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSessionToDiscard',
        ),
    ]
