# Generated by Django 2.2.1 on 2019-07-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0049_delete_gamesessiontodiscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.SmallIntegerField(),
        ),
    ]
