# Generated by Django 2.2.1 on 2019-07-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0050_auto_20190728_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(),
        ),
    ]
