# Generated by Django 2.2.1 on 2019-07-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0051_auto_20190728_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['year', 'season', 'day_start', 'day_end', 'description', 'game_no']},
        ),
    ]
