# Generated by Django 2.2.1 on 2019-07-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0052_auto_20190728_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificlocation',
            name='general_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='specific_locations', to='history.GeneralLocation'),
            preserve_default=False,
        ),
    ]
