# Generated by Django 2.2.1 on 2019-07-30 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0053_specificlocation_general_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specificlocation',
            name='general_location',
        ),
    ]
