# Generated by Django 2.2.1 on 2019-08-01 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0055_specificlocation_general_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='history.GameSession'),
        ),
    ]
