# Generated by Django 2.2.1 on 2019-08-01 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0056_auto_20190801_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='history.GameSession'),
        ),
    ]
