# Generated by Django 2.2.1 on 2019-08-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0058_auto_20190801_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='describedevent',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
