# Generated by Django 2.2.1 on 2019-08-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190801_1152'),
        ('history', '0059_auto_20190806_0742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DescribedEvent',
            new_name='ChronicleEvent',
        ),
    ]
    atomic = False