# Generated by Django 2.2.1 on 2019-08-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190801_1152'),
        ('history', '0060_auto_20190806_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='TimelineEvent',
        ),
    ]
    atomic = False