# Generated by Django 2.2.1 on 2019-08-06 08:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0061_auto_20190806_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DescribedEventNote',
            new_name='ChronicleEventNote',
        ),
        migrations.RenameModel(
            old_name='EventNote',
            new_name='TimelineEventNote',
        ),
    ]
