# Generated by Django 4.0.2 on 2022-03-23 17:36

import chronicles.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    # replaces = [('chronicles', '0001_initial'), ('chronicles', '0002_auto_20210106_1613'), ('chronicles', '0003_timeunit_picture_sets'), ('chronicles', '0004_remove_timeunit_pictures'), ('chronicles', '0005_auto_20211017_1457'), ('chronicles', '0006_plotthread'), ('chronicles', '0007_timeunit_plot_threads'), ('chronicles', '0008_auto_20211017_1514'), ('chronicles', '0009_auto_20211017_1531'), ('chronicles', '0010_alter_date_options'), ('chronicles', '0011_timeunit_new_debates'), ('chronicles', '0012_alter_timeunit_new_debates'), ('chronicles', '0013_remove_timeunit_debates'), ('chronicles', '0014_rename_new_debates_timeunit_debates'), ('chronicles', '0015_alter_timeunit_debates'), ('chronicles', '0016_alter_timeunit_debates'), ('chronicles', '0017_alter_timeunit_debates_alter_timeunit_known_directly_and_more'), ('chronicles', '0018_alter_timeunit_known_directly_and_more')]

    initial = True

    dependencies = [
        ('imaginarion', '0001_initial'),
        ('imaginarion', '0012_pictureset'),
        ('communications', '0001_0001_initial_squashed'),
        ('users', '0001_initial'),
        ('toponomikon', '0001_0001_initial_squashed'),
        ('users', '0016_profile_user_image'),
        ('users', '0007_auto_20210106_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_features_pics')),
            ],
            options={
                'verbose_name': 'I. Chapter',
                'ordering': ['chapter_no'],
            },
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(blank=True, choices=[('1', 'Wiosny'), ('2', 'Lata'), ('3', 'Jesieni'), ('4', 'Zimy')], max_length=6, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(90)])),
            ],
            options={
                'verbose_name': '- Date',
                'unique_together': {('year', 'season', 'day')},
                'ordering': ['year', 'day'],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_no', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to='chronicles.chapter')),
            ],
            options={
                'verbose_name': 'II. Game session',
                'ordering': ['game_no'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': '- Thread',
                'ordering': ['sorting_name'],
            },
        ),
        migrations.CreateModel(
            name='TimeUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('name_genetive', models.CharField(blank=True, max_length=256, null=True)),
                ('event_no_in_game', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('description_short', models.TextField(blank=True, null=True)),
                ('description_long', models.TextField(blank=True, null=True)),
                ('date_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timeunits_ended', to='chronicles.date', verbose_name='Date end (year of the encompassing unit)')),
                ('date_start', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timeunits_started', to='chronicles.date', verbose_name='Date start (year of the encompassing unit)')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_events', to='chronicles.gamesession')),
                ('in_timeunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timeunits', to='chronicles.timeunit')),
                ('known_directly', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='events_known_directly', to='users.Profile')),
                ('known_indirectly', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='events_known_indirectly', to='users.Profile')),
                ('threads', models.ManyToManyField(blank=True, related_name='events', to='chronicles.Thread')),
                ('locations', models.ManyToManyField(blank=True, related_name='events', to='toponomikon.Location')),
                ('known_long_desc', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='timeunits_long_desc', to='users.Profile')),
                ('known_short_desc', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='timeunits_known_short_desc', to='users.Profile')),
                ('date_in_chronology', models.CharField(blank=True, max_length=99, null=True)),
                ('date_in_era', models.CharField(blank=True, max_length=99, null=True)),
                ('date_in_period', models.CharField(blank=True, max_length=99, null=True)),
                ('debates', models.ManyToManyField(blank=True, limit_choices_to={'kind': 'Debate'}, related_name='events', to='communications.Thread')),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='imaginarion.audio')),
                ('picture_sets', models.ManyToManyField(blank=True, related_name='events', to='imaginarion.PictureSet')),
            ],
            options={
                'verbose_name_plural': '* Time Units (Time spans, History events, Game events)',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Chronology',
            fields=[
            ],
            options={
                'verbose_name_plural': '1 - Chronologies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chronicles.timeunit',),
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
            ],
            options={
                'verbose_name': '2 - Era',
                'ordering': ['in_timeunit'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chronicles.timeunit',),
        ),
        migrations.CreateModel(
            name='HistoryEvent',
            fields=[
            ],
            options={
                'verbose_name': '4 - History Event',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chronicles.timeunit',),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
            ],
            options={
                'verbose_name': '3 - Period',
                'ordering': ['in_timeunit'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chronicles.timeunit',),
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
            ],
            options={
                'verbose_name': 'III. Game event',
                'ordering': ['game', 'event_no_in_game'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chronicles.timeunit',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chronicles.timeunit',),
        ),
        migrations.CreateModel(
            name='ThreadActive',
            fields=[
            ],
            options={
                'verbose_name': '- Active Thread',
                'verbose_name_plural': '- Threads Active',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chronicles.thread',),
        ),
        migrations.CreateModel(
            name='ThreadEnded',
            fields=[
            ],
            options={
                'verbose_name': '- Ended Thread',
                'verbose_name_plural': '- Threads Ended',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chronicles.thread',),
        ),
        migrations.DeleteModel(
            name='ThreadActive',
        ),
        migrations.DeleteModel(
            name='ThreadEnded',
        ),
        migrations.CreateModel(
            name='PlotThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': '- Thread',
                'ordering': ['sorting_name'],
            },
            managers=[
                ('plot_threads_ended', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='timeunit',
            name='plot_threads',
            field=models.ManyToManyField(blank=True, related_name='events', to='chronicles.PlotThread'),
        ),
        migrations.AlterModelManagers(
            name='plotthread',
            managers=[
            ],
        ),
        migrations.AlterModelOptions(
            name='plotthread',
            options={'ordering': ['sorting_name'], 'verbose_name': '- PlotThread'},
        ),
        migrations.RemoveField(
            model_name='timeunit',
            name='threads',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_directly',
            field=models.ManyToManyField(blank=True, related_name='events_known_directly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_indirectly',
            field=models.ManyToManyField(blank=True, related_name='events_known_indirectly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_long_desc',
            field=models.ManyToManyField(blank=True, related_name='timeunits_long_desc', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_short_desc',
            field=models.ManyToManyField(blank=True, related_name='timeunits_known_short_desc', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_directly',
            field=models.ManyToManyField(blank=True, limit_choices_to=chronicles.models.non_GM, related_name='events_known_directly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_indirectly',
            field=models.ManyToManyField(blank=True, limit_choices_to=chronicles.models.non_GM, related_name='events_known_indirectly', to='users.Profile'),
        ),
    ]
