# Generated by Django 4.0.4 on 2022-08-26 14:55

from django.db import migrations
import rpg_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plotthread',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')], 'verbose_name': '- PlotThread'},
        ),
    ]
