# Generated by Django 2.2.1 on 2020-07-04 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='event_no_in_game',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
