# Generated by Django 2.2.1 on 2020-06-27 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='in_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='chronicles.Period'),
        ),
    ]
