# Generated by Django 4.0.4 on 2022-05-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0002_alter_chapter_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plotthread',
            options={'ordering': ['name'], 'verbose_name': '- PlotThread'},
        ),
        migrations.RemoveField(
            model_name='plotthread',
            name='sorting_name',
        ),
    ]
