# Generated by Django 4.1.7 on 2023-02-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0002_alter_plotthread_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['order_no'], 'verbose_name': 'II. Game session'},
        ),
        migrations.AddField(
            model_name='gamesession',
            name='order_no',
            field=models.IntegerField(null=True),
        ),
    ]
