# Generated by Django 2.2.1 on 2020-07-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0002_auto_20200704_0833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_no'], 'verbose_name': '** Chapter'},
        ),
        migrations.AlterModelOptions(
            name='gameevent',
            options={'ordering': ['game', 'event_no_in_game'], 'verbose_name': '*** Game event'},
        ),
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['game_no'], 'verbose_name': '* Game session'},
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='game',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='chronicles.GameSession'),
        ),
    ]
