# Generated by Django 2.2.1 on 2020-06-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0002_period_in_period'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='date',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='date',
            name='year_of_period',
        ),
        migrations.RemoveField(
            model_name='historicalevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='period',
            name='chronology_system',
        ),
        migrations.RemoveField(
            model_name='period',
            name='in_period',
        ),
        migrations.AlterUniqueTogether(
            name='yearofperiod',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='yearofperiod',
            name='period',
        ),
        migrations.DeleteModel(
            name='ChronologySystem',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='HistoricalEvent',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='YearOfPeriod',
        ),
    ]
