# Generated by Django 4.0.2 on 2022-03-25 11:16

import chronicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('chronicles', '0002_rename_known_directly_timeunit_witnesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='witnesses',
            field=models.ManyToManyField(blank=True, limit_choices_to=chronicles.models.non_GM, related_name='events_witnessed', to='users.Profile'),
        ),
    ]
