# Generated by Django 4.0.2 on 2022-03-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0003_alter_timeunit_witnesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeunit',
            old_name='witnesses',
            new_name='participants',
        ),
    ]
