# Generated by Django 3.1 on 2021-09-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0003_timeunit_picture_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeunit',
            name='pictures',
        ),
    ]
