# Generated by Django 2.2.1 on 2020-07-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0001_initial'),
        ('chronicles', '0004_auto_20200705_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='tertiary_locations',
            field=models.ManyToManyField(blank=True, related_name='events_as_tertiary_loc', to='toponomikon.TertiaryLocation'),
        ),
    ]
