# Generated by Django 2.2.1 on 2020-06-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0004_chronology_date_era_event_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='era',
            options={'ordering': ['chronology__id', 'order_no']},
        ),
        migrations.RenameField(
            model_name='era',
            old_name='year_start_in_chronology',
            new_name='years_span',
        ),
        migrations.RemoveField(
            model_name='era',
            name='year_end_in_chronology',
        ),
        migrations.RemoveField(
            model_name='era',
            name='year_start_to_traegharon_era_start',
        ),
        migrations.AddField(
            model_name='chronology',
            name='start_year_rel_to_traegharon_era',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='era',
            name='order_no',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
