# Generated by Django 4.0.2 on 2022-03-25 11:40

import chronicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('chronicles', '0004_rename_witnesses_timeunit_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='participants',
            field=models.ManyToManyField(blank=True, limit_choices_to=chronicles.models.non_GM, related_name='events_participated', to='users.Profile'),
        ),
    ]
