# Generated by Django 4.1.7 on 2023-05-31 20:25

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chronicles', '0004_gamesession_ispublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=5),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='gamesessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
