# Generated by Django 3.1 on 2021-10-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0004_remove_timeunit_pictures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreadActive',
        ),
        migrations.DeleteModel(
            name='ThreadEnded',
        ),
    ]
