# Generated by Django 3.1 on 2021-10-17 12:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0005_auto_20211017_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': '- Thread',
                'ordering': ['sorting_name'],
            },
            managers=[
                ('plot_threads_ended', django.db.models.manager.Manager()),
            ],
        ),
    ]
