# Generated by Django 2.2.1 on 2020-06-27 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toponomikon', '0015_auto_20200627_2324'),
        ('chronicles', '0006_auto_20200627_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='primary_locations',
            field=models.ManyToManyField(related_name='events_as_primary_loc', to='toponomikon.PrimaryLocation'),
        ),
        migrations.AddField(
            model_name='event',
            name='secondary_locations',
            field=models.ManyToManyField(related_name='events_as_secondary_loc', to='toponomikon.SecondaryLocation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='in_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='chronicles.Event'),
        ),
    ]
