# Generated by Django 2.2.1 on 2020-07-07 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0007_timeunit_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='chronicles.GameSession'),
        ),
    ]
