# Generated by Django 3.1 on 2021-10-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0007_timeunit_plot_threads'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='plotthread',
            managers=[
            ],
        ),
    ]
