# Generated by Django 3.1 on 2021-10-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0008_auto_20211017_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plotthread',
            options={'ordering': ['sorting_name'], 'verbose_name': '- PlotThread'},
        ),
        migrations.RemoveField(
            model_name='timeunit',
            name='threads',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
