# Generated by Django 3.2.8 on 2021-11-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0009_auto_20211017_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='date',
            options={'ordering': ['year', 'day'], 'verbose_name': '- Date'},
        ),
    ]
