# Generated by Django 2.2.1 on 2020-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0010_auto_20200709_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='year_ab_urbe_condita',
        ),
        migrations.RemoveField(
            model_name='timeunit',
            name='dates',
        ),
        migrations.AddField(
            model_name='timeunit',
            name='date_in_chronology',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='timeunit',
            name='date_in_era',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='timeunit',
            name='date_in_period',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='season',
            field=models.CharField(blank=True, choices=[('Wiosny', 'Wiosny'), ('Lata', 'Lata'), ('Jesieni', 'Jesieni'), ('Zimy', 'Zimy')], max_length=6, null=True),
        ),
    ]
