# Generated by Django 3.2.8 on 2022-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0014_alter_thread_topic'),
        ('chronicles', '0010_alter_date_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='new_debates',
            field=models.ManyToManyField(blank=True, related_name='eventss', to='communications.Debate'),
        ),
    ]
