# Generated by Django 2.2.1 on 2020-07-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0011_auto_20200712_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='season',
            field=models.CharField(blank=True, choices=[('1', 'Wiosny'), ('2', 'Lata'), ('3', 'Jesieni'), ('4', 'Zimy')], max_length=6, null=True),
        ),
    ]
