# Generated by Django 3.2.8 on 2022-01-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0012_alter_timeunit_new_debates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeunit',
            name='debates',
        ),
    ]
