# Generated by Django 3.2.8 on 2022-01-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0013_remove_timeunit_debates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeunit',
            old_name='new_debates',
            new_name='debates',
        ),
    ]
