# Generated by Django 3.1 on 2020-09-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0006_remove_debate_allowed_profiles'),
        ('chronicles', '0013_auto_20200713_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeunit',
            name='debates',
            field=models.ManyToManyField(blank=True, related_name='events', to='debates.Debate'),
        ),
    ]
