# Generated by Django 3.2.8 on 2022-01-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0015_auto_20220109_1758'),
        ('chronicles', '0014_rename_new_debates_timeunit_debates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='debates',
            field=models.ManyToManyField(blank=True, related_name='events', to='communications.Thread'),
        ),
    ]
