# Generated by Django 4.0.2 on 2022-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0016_alter_debate_options'),
        ('chronicles', '0015_alter_timeunit_debates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='debates',
            field=models.ManyToManyField(blank=True, related_name='events', to='communications.Debate'),
        ),
    ]
