# Generated by Django 3.1 on 2020-11-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronicles', '0015_threadactive_threadended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeunit',
            name='debate',
        ),
    ]
