# Generated by Django 4.0.2 on 2022-03-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_user_image'),
        ('communications', '0017_announcementstatement_debatestatement_and_more'),
        ('chronicles', '0016_alter_timeunit_debates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='debates',
            field=models.ManyToManyField(blank=True, limit_choices_to={'kind': 'Debate'}, related_name='events', to='communications.Thread'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_directly',
            field=models.ManyToManyField(blank=True, related_name='events_known_directly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_indirectly',
            field=models.ManyToManyField(blank=True, related_name='events_known_indirectly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_long_desc',
            field=models.ManyToManyField(blank=True, related_name='timeunits_long_desc', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_short_desc',
            field=models.ManyToManyField(blank=True, related_name='timeunits_known_short_desc', to='users.Profile'),
        ),
    ]
