# Generated by Django 4.0.2 on 2022-03-18 20:27

import chronicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_user_image'),
        ('chronicles', '0017_alter_timeunit_debates_alter_timeunit_known_directly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeunit',
            name='known_directly',
            field=models.ManyToManyField(blank=True, limit_choices_to=chronicles.models.non_GM, related_name='events_known_directly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='timeunit',
            name='known_indirectly',
            field=models.ManyToManyField(blank=True, limit_choices_to=chronicles.models.non_GM, related_name='events_known_indirectly', to='users.Profile'),
        ),
    ]
