# Generated by Django 3.1 on 2020-09-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200926_1248'),
        ('rules', '0017_auto_20200926_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileKlass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveSmallIntegerField()),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_klasses', to='rules.klass')),
                ('profile', models.ManyToManyField(related_name='profile_klasses', to='users.Profile')),
            ],
            options={
                'verbose_name': 'Profile Klass',
                'verbose_name_plural': 'Profile Klasses',
                'ordering': ['profile__character_name'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile', models.ManyToManyField(blank=True, related_name='achievements', to='users.Profile')),
            ],
        ),
    ]
