# Generated by Django 3.1 on 2021-01-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileklass',
            options={'ordering': ['profile__name'], 'verbose_name': 'Profile Klass', 'verbose_name_plural': 'Profile Klasses'},
        ),
    ]
