# Generated by Django 3.1 on 2020-09-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200926_1248'),
        ('development', '0002_auto_20200926_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='profile',
        ),
        migrations.AddField(
            model_name='achievement',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='users.profile'),
            preserve_default=False,
        ),
    ]
