# Generated by Django 3.1 on 2021-01-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_auto_20210103_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileklass',
            options={'ordering': ['profile__persona__name'], 'verbose_name': 'Profile Klass', 'verbose_name_plural': 'Profile Klasses'},
        ),
    ]
