# Generated by Django 3.1 on 2021-01-17 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0003_auto_20210103_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileklass',
            options={'ordering': ['profile__character__name'], 'verbose_name': 'Profile Klass', 'verbose_name_plural': 'Profile Klasses'},
        ),
    ]
