# Generated by Django 3.1 on 2020-09-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0003_auto_20200926_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileklass',
            name='experience',
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.PositiveSmallIntegerField()),
                ('experience', models.PositiveSmallIntegerField()),
                ('achievements', models.ManyToManyField(blank=True, related_name='levels', to='development.Achievement')),
                ('profile_klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='development.profileklass')),
            ],
            options={
                'ordering': ['profile_klass', 'level_number'],
            },
        ),
    ]
