# Generated by Django 3.1 on 2021-03-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0004_auto_20210117_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileklass',
            options={'ordering': ['profile__character__first_name'], 'verbose_name': 'Profile Klass', 'verbose_name_plural': 'Profile Klasses'},
        ),
    ]
