# Generated by Django 3.1 on 2020-09-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0005_auto_20200926_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_mods',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
