# Generated by Django 3.2.8 on 2022-02-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0005_auto_20210310_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='level',
            name='profile_klass',
        ),
        migrations.RemoveField(
            model_name='profileklass',
            name='klass',
        ),
        migrations.RemoveField(
            model_name='profileklass',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='ProfileKlass',
        ),
    ]
