from django.test import TestCase
from django.urls import reverse, resolve
from news import views
from news.models import News
from users.models import User


class UnfollowNewsTest(TestCase):
    def setUp(self):
        self.user1 = User.objects.create_user(username='user1', password='pass1111')
        self.user2 = User.objects.create_user(username='user2', password='pass1111')

        self.news1 = News.objects.create(title='News1', text='news1', author=self.user1)
        self.news1.allowed_profiles.set([self.user1.profile, ])

        self.url = reverse('news:follow', kwargs={'news_id': self.news1.id})

    def test_login_required(self):
        redirect_url = reverse('users:login') + '?next=' + self.url
        response = self.client.get(self.url)
        self.assertRedirects(response, redirect_url, status_code=302, target_status_code=200)

    def test_redirect_if_unallowed(self):
        self.client.force_login(self.user2)
        redirect_url = reverse('home:dupa')
        response = self.client.get(self.url)
        self.assertRedirects(response, redirect_url, status_code=302, target_status_code=200)

    def test_404(self):
        self.client.force_login(self.user1)
        url = reverse('news:unfollow', kwargs={'news_id': self.news1.id + 999})
        response = self.client.get(url)
        self.assertEquals(response.status_code, 404)

    def test_redirect_if_allowed(self):
        self.client.force_login(self.user1)
        redirect_url = reverse('news:detail', kwargs={'news_id': self.news1.id})
        response = self.client.get(self.url)
        self.assertRedirects(response, redirect_url, status_code=302, target_status_code=200)

    # No test_get - no template generated by unfollow_news_view()

    def test_url_resolves_view(self):
        view = resolve(f'/news/news-detail:{self.news1.id}/unfollow')
        self.assertEquals(view.func, views.unfollow_news_view)
