# Generated by Django 4.0.4 on 2022-07-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='version_of',
        ),
    ]
