# Generated by Django 4.0.2 on 2022-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='allowees',
            field=models.ManyToManyField(blank=True, related_name='professions_allowed', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='allowees',
            field=models.ManyToManyField(blank=True, related_name='allowed_klasses', to='users.Profile'),
        ),
    ]
