# Generated by Django 2.2.1 on 2020-07-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksSkill',
            fields=[
            ],
            options={
                'verbose_name': 'Księgi',
                'verbose_name_plural': 'Skills - BOOKS',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skill',),
        ),
        migrations.CreateModel(
            name='TheologySkill',
            fields=[
            ],
            options={
                'verbose_name': 'Teologia',
                'verbose_name_plural': 'Skills - THEOLOGY',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skill',),
        ),
        migrations.AlterModelOptions(
            name='synergy',
            options={'ordering': ['sorting_name'], 'verbose_name': 'synergy', 'verbose_name_plural': 'synergies'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='tested_trait',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cecha/Cechy'),
        ),
    ]
