# Generated by Django 4.0.2 on 2022-04-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='is_elite',
        ),
        migrations.AddField(
            model_name='profession',
            name='type',
            field=models.CharField(choices=[('Pospolite', 'Pospolite'), ('Elitarne', 'Elitarne'), ('Ezoteryczne', 'Ezoteryczne')], default='Pospolite', max_length=50),
        ),
    ]
