# Generated by Django 4.0.2 on 2022-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shield',
            name='armor_class_bonus',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
