# Generated by Django 3.2.8 on 2022-01-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_squashed_0005_auto_20211017_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapontype',
            name='description',
        ),
    ]
