# Generated by Django 4.0.2 on 2022-04-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_remove_profession_is_elite_profession_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='type',
            field=models.CharField(choices=[('Pospolite', 'Pospolite'), ('Elitarne', 'Elitarne'), ('Hermetyczne', 'Hermetyczne')], max_length=50),
        ),
    ]
