# Generated by Django 4.0.4 on 2022-05-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_skill_options_alter_skill_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='sorting_name',
        ),
    ]
