# Generated by Django 2.2.1 on 2020-08-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20200721_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorySkill',
            fields=[
            ],
            options={
                'verbose_name': 'Historia',
                'verbose_name_plural': 'Skills - HISTORY',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skill',),
        ),
    ]
