# Generated by Django 3.1 on 2020-09-26 09:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('rules', '0003_historyskill'),
    ]

    operations = [
        migrations.RenameModel('PlateType', 'Plate')
    ]
