# Generated by Django 4.0.2 on 2022-04-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_remove_klass_lvl_1_remove_klass_lvl_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProfession',
            fields=[
            ],
            options={
                'verbose_name': '--- SubProfession',
                'verbose_name_plural': '--- SubProfessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.profession',),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_elite',
            field=models.BooleanField(default=False),
        ),
    ]
