# Generated by Django 4.0.4 on 2022-05-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_remove_skill_sorting_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['name'], 'verbose_name': 'Profession', 'verbose_name_plural': '--- PROFESSIONS'},
        ),
        migrations.AlterModelOptions(
            name='skillkind',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skilllevel',
            options={'ordering': ['skill__name', 'level']},
        ),
        migrations.AlterModelOptions(
            name='skilltype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subprofession',
            options={'ordering': ['name'], 'verbose_name': 'SubProfession', 'verbose_name_plural': '--- SUBPROFESSIONS'},
        ),
        migrations.AlterModelOptions(
            name='synergy',
            options={'ordering': ['name'], 'verbose_name': 'Synergy', 'verbose_name_plural': 'Synergies'},
        ),
        migrations.AlterModelOptions(
            name='synergylevel',
            options={'ordering': ['synergy', 'level']},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='weapontype',
            options={'ordering': ['name'], 'verbose_name': 'Weapon type', 'verbose_name_plural': 'Weapon types'},
        ),
        migrations.RemoveField(
            model_name='profession',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='skillkind',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='skilltype',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='subprofession',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='synergy',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='synergylevel',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='sorting_name',
        ),
        migrations.RemoveField(
            model_name='weapontype',
            name='sorting_name',
        ),
    ]
