# Generated by Django 4.0.4 on 2022-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_remove_skilllevel_acquired_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sphragis',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
