# Generated by Django 4.0.2 on 2022-04-24 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial_squashed'),
        ('rules', '0003_alter_profession_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProfession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('sorting_name', models.CharField(blank=True, max_length=250, null=True)),
                ('allowees', models.ManyToManyField(blank=True, related_name='subprofessions_allowed', to='users.Profile')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subprofessions', to='rules.profession')),
                ('starting_skills', models.ManyToManyField(blank=True, to='rules.Skill')),
            ],
            options={
                'verbose_name': 'SubProfession',
                'verbose_name_plural': '--- SUBPROFESSIONS',
                'ordering': ['sorting_name'],
            },
        ),
    ]
