# Generated by Django 3.1 on 2021-10-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_auto_20210922_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synergy',
            options={'ordering': ['sorting_name'], 'verbose_name': 'Synergy', 'verbose_name_plural': 'Synergies'},
        ),
        migrations.AlterField(
            model_name='synergy',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
