# Generated by Django 4.0.4 on 2022-08-26 14:55

from django.db import migrations
import rpg_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_sphragis_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='combattype',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')]},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': [rpg_project.utils.OrderByPolish('text')]},
        ),
        migrations.AlterModelOptions(
            name='perk',
            options={'ordering': [rpg_project.utils.OrderByPolish('name'), rpg_project.utils.OrderByPolish('description')]},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')], 'verbose_name': 'Profession', 'verbose_name_plural': '--- PROFESSIONS'},
        ),
        migrations.AlterModelOptions(
            name='rulescomment',
            options={'ordering': [rpg_project.utils.OrderByPolish('text')]},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')]},
        ),
        migrations.AlterModelOptions(
            name='skillgroup',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')]},
        ),
        migrations.AlterModelOptions(
            name='skillkind',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')]},
        ),
        migrations.AlterModelOptions(
            name='skilllevel',
            options={'ordering': [rpg_project.utils.OrderByPolish('skill__name'), 'level']},
        ),
        migrations.AlterModelOptions(
            name='skilltype',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')]},
        ),
        migrations.AlterModelOptions(
            name='sphragis',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')]},
        ),
        migrations.AlterModelOptions(
            name='subprofession',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')], 'verbose_name': 'SubProfession', 'verbose_name_plural': '--- SUBPROFESSIONS'},
        ),
        migrations.AlterModelOptions(
            name='synergy',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')], 'verbose_name': 'Synergy', 'verbose_name_plural': 'Synergies'},
        ),
        migrations.AlterModelOptions(
            name='synergylevel',
            options={'ordering': [rpg_project.utils.OrderByPolish('synergy__name'), 'level']},
        ),
        migrations.AlterModelOptions(
            name='weapontype',
            options={'ordering': [rpg_project.utils.OrderByPolish('name')]},
        ),
    ]
