# Generated by Django 4.0.2 on 2022-04-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_subprofession_profession_is_elite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subprofessions', to='rules.profession'),
        ),
    ]
