# Generated by Django 4.0.2 on 2022-04-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_subprofession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimaryProfession',
        ),
        migrations.DeleteModel(
            name='SecondaryProfession',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='starting_skills',
        ),
    ]
