# Generated by Django 4.0.4 on 2022-05-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_alter_profession_options_alter_skillkind_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='is_version',
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='is_version',
        ),
        migrations.AddField(
            model_name='skill',
            name='version_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rules.skill'),
        ),
    ]
