# Generated by Django 3.2.8 on 2022-01-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_auto_20220117_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tested_trait',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
