# Generated by Django 4.0.2 on 2022-04-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_profession_profession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubProfession',
        ),
        migrations.CreateModel(
            name='PrimaryProfession',
            fields=[
            ],
            options={
                'verbose_name': '--- Primary Profession',
                'verbose_name_plural': '--- Primary Professions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.profession',),
        ),
        migrations.CreateModel(
            name='SecondaryProfession',
            fields=[
            ],
            options={
                'verbose_name': '--- Secondary Profession',
                'verbose_name_plural': '--- Secondary Professions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.profession',),
        ),
        migrations.AlterField(
            model_name='profession',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssecondary_professions', to='rules.profession'),
        ),
    ]
