# Generated by Django 4.0.4 on 2022-06-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_remove_skill_is_version_remove_skilllevel_is_version_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BooksSkill',
        ),
        migrations.DeleteModel(
            name='HistorySkill',
        ),
        migrations.DeleteModel(
            name='TheologySkill',
        ),
    ]
