# Generated by Django 4.0.4 on 2022-10-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_combattype_options_alter_condition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagetype',
            name='description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
