# Generated by Django 3.1 on 2020-09-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200926_1107'),
        ('rules', '0005_auto_20200926_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'active_player'), ('status', 'inactive_player'), ('status', 'dead_player'), _connector='OR'), related_name='allowed_plates', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'active_player'), ('status', 'inactive_player'), ('status', 'dead_player'), _connector='OR'), related_name='allowed_shields', to='users.Profile'),
        ),
    ]
