# Generated by Django 4.0.4 on 2022-06-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_delete_booksskill_delete_historyskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalSkill',
            fields=[
            ],
            options={
                'verbose_name': 'Skill - MENTALNE',
                'verbose_name_plural': 'Skills - MENTALNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skill',),
        ),
        migrations.CreateModel(
            name='PriestsSkill',
            fields=[
            ],
            options={
                'verbose_name': 'Skill - MOCE KAPŁAŃSKIE',
                'verbose_name_plural': 'Skills - MOCE KAPŁAŃSKIE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skill',),
        ),
        migrations.CreateModel(
            name='RegularSkill',
            fields=[
            ],
            options={
                'verbose_name': 'Skill - POWSZECHNE',
                'verbose_name_plural': 'Skills - POWSZECHNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skill',),
        ),
        migrations.CreateModel(
            name='SorcerersSkill',
            fields=[
            ],
            options={
                'verbose_name': 'Skill - ZAKLĘCIA',
                'verbose_name_plural': 'Skills - ZAKLĘCIA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skill',),
        ),
        migrations.CreateModel(
            name='TheurgistsSkill',
            fields=[
            ],
            options={
                'verbose_name': 'Skill - MOCE TEURGICZNE',
                'verbose_name_plural': 'Skills - MOCE TEURGICZNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skill',),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='sphragis',
        ),
        migrations.DeleteModel(
            name='Sphragis',
        ),
    ]
