# Generated by Django 4.0.2 on 2022-04-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_delete_subprofession_primaryprofession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_professions', to='rules.profession'),
        ),
    ]
