# Generated by Django 4.0.4 on 2022-12-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_alter_damagetype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='weapon',
            new_name='weapon_type',
        ),
    ]
