# Generated by Django 3.1 on 2020-09-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200926_1107'),
        ('rules', '0007_auto_20200926_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'active_player'), ('status', 'inactive_player'), ('status', 'dead_player'), _connector='OR'), related_name='allowed_weapons', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weapons', to='rules.weaponclass'),
        ),
    ]
