# Generated by Django 4.1.7 on 2023-05-27 16:02

from django.db import migrations, models
import rpg_project.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_image_icons_color'),
        ('rules', '0007_rename_weapon_skill_weapon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_genitive', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'ordering': [rpg_project.utils.OrderByPolish('name')],
            },
        ),
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Kapłańskie', 'Kapłańskie'), ('Teurgiczne', 'Teurgiczne'), ('Magiczne', 'Magiczne')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_second', models.CharField(blank=True, max_length=100, null=True)),
                ('name_origin', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('range', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('radius', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('damage', models.CharField(blank=True, max_length=20, null=True)),
                ('saving_throw_malus', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saving_throw_trait', models.CharField(blank=True, choices=[('Moc', 'Moc'), ('Sił', 'Sił'), ('Zrc', 'Zrc'), ('Kon', 'Kon'), ('Sił/Zrc', 'Sił/Zrc'), ('Sił/Kon', 'Sił/Kon'), ('Zrc/Kon', 'Zrc/Kon'), ('Sił/Zrc/Kon', 'Sił/Zrc/Kon')], max_length=20, null=True)),
                ('allowees', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='allowed_spells', to='users.profile')),
                ('domains', models.ManyToManyField(related_name='spells', to='rules.domain')),
                ('spheres', models.ManyToManyField(related_name='spells', to='rules.sphere')),
            ],
            options={
                'ordering': ['level', rpg_project.utils.OrderByPolish('name')],
            },
        ),
        migrations.CreateModel(
            name='PriestSpell',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.spell',),
        ),
    ]
