# Generated by Django 4.0.2 on 2022-04-30 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_remove_subprofession_developed_skilllevels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sphragis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='is_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.weapon'),
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='is_version',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='sphragis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.sphragis'),
        ),
    ]
