# Generated by Django 4.0.2 on 2022-04-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_alter_profession_profession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='primaryprofession',
            options={'verbose_name': 'Primary Profession', 'verbose_name_plural': '--- Primary Professions'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['sorting_name'], 'verbose_name': 'Profession', 'verbose_name_plural': '--- PROFESSIONS'},
        ),
        migrations.AlterModelOptions(
            name='secondaryprofession',
            options={'verbose_name': 'Secondary Profession', 'verbose_name_plural': '--- Secondary Professions'},
        ),
    ]
