# Generated by Django 4.0.4 on 2022-06-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_mentalskill_priestsskill_regularskill_sorcerersskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalSkillLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Skill Level - MENTALNE',
                'verbose_name_plural': 'Skill Levels - MENTALNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skilllevel',),
        ),
        migrations.CreateModel(
            name='MentalSynergy',
            fields=[
            ],
            options={
                'verbose_name': 'Synergy - MENTALNE',
                'verbose_name_plural': 'Synergies - MENTALNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.synergy',),
        ),
        migrations.CreateModel(
            name='MentalSynergyLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Synergy Level - MENTALNE',
                'verbose_name_plural': 'Synergy Levels - MENTALNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.synergylevel',),
        ),
        migrations.CreateModel(
            name='PriestsSkillLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Skill Level - MOCE KAPŁAŃSKIE',
                'verbose_name_plural': 'Skill Levels - MOCE KAPŁAŃSKIE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skilllevel',),
        ),
        migrations.CreateModel(
            name='RegularSkillLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Skill Level - POWSZECHNE',
                'verbose_name_plural': 'Skill Levels - POWSZECHNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skilllevel',),
        ),
        migrations.CreateModel(
            name='RegularSynergy',
            fields=[
            ],
            options={
                'verbose_name': 'Synergy - POWSZECHNE',
                'verbose_name_plural': 'Synergies - POWSZECHNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.synergy',),
        ),
        migrations.CreateModel(
            name='RegularSynergyLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Synergy Level - POWSZECHNE',
                'verbose_name_plural': 'Synergy Levels - POWSZECHNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.synergylevel',),
        ),
        migrations.CreateModel(
            name='SorcerersSkillLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Skill Level - ZAKLĘCIA',
                'verbose_name_plural': 'Skill Levels - ZAKLĘCIA',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skilllevel',),
        ),
        migrations.CreateModel(
            name='TheurgistsSkillLevel',
            fields=[
            ],
            options={
                'verbose_name': 'Skill Level - MOCE TEURGICZNE',
                'verbose_name_plural': 'Skill Levels - MOCE TEURGICZNE',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.skilllevel',),
        ),
    ]
