# Generated by Django 3.2.8 on 2022-01-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_skilltype_sorting_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sorting_name', models.CharField(blank=True, max_length=101, null=True)),
            ],
            options={
                'ordering': ['sorting_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='skilltype',
            options={'ordering': ['kind', 'sorting_name']},
        ),
        migrations.AddField(
            model_name='skilltype',
            name='kinds',
            field=models.ManyToManyField(blank=True, related_name='skill_types', to='rules.SkillKind'),
        ),
    ]
