# Generated by Django 4.0.2 on 2022-04-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_alter_primaryprofession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eliteprofession',
            name='allowees',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='allowees',
        ),
        migrations.RemoveField(
            model_name='klass',
            name='profession',
        ),
        migrations.DeleteModel(
            name='EliteKlass',
        ),
        migrations.DeleteModel(
            name='EliteProfession',
        ),
        migrations.DeleteModel(
            name='Klass',
        ),
    ]
