# Generated by Django 4.1.7 on 2023-05-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_domain_sphere_spell_priestspell'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorcererSpell',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.spell',),
        ),
        migrations.CreateModel(
            name='TheurgistSpell',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rules.spell',),
        ),
    ]
