# Generated by Django 3.2.8 on 2022-01-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_auto_20220118_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilltype',
            options={'ordering': ['sorting_name']},
        ),
        migrations.RemoveField(
            model_name='skilltype',
            name='kind',
        ),
    ]
