# Generated by Django 4.0.4 on 2022-06-12 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_mentalskilllevel_mentalsynergy_mentalsynergylevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.weapon'),
        ),
    ]
