# Generated by Django 4.1.7 on 2023-05-27 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prosoponomikon', '0018_alter_acquisition_unique_together_and_more'),
        ('rules', '0009_sorcererspell_theurgistspell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sphragis',
        ),
        migrations.DeleteModel(
            name='PriestsSkill',
        ),
        migrations.DeleteModel(
            name='PriestsSkillLevel',
        ),
        migrations.DeleteModel(
            name='SorcerersSkill',
        ),
        migrations.DeleteModel(
            name='SorcerersSkillLevel',
        ),
        migrations.DeleteModel(
            name='TheurgistsSkill',
        ),
        migrations.DeleteModel(
            name='TheurgistsSkillLevel',
        ),
    ]
