# Generated by Django 3.2.8 on 2022-01-18 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_auto_20220118_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill_groups', to='rules.skilltype'),
        ),
    ]
