# Generated by Django 4.0.4 on 2022-06-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_alter_skill_weapon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='weapon_type',
        ),
        migrations.DeleteModel(
            name='WeaponType',
        ),
    ]
