# Generated by Django 3.2.8 on 2022-01-18 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_skillgroup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillgroup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_groups', to='rules.skilltype'),
        ),
    ]
