# Generated by Django 4.1.7 on 2023-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_delete_sphragis_delete_priestsskill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='damage',
        ),
        migrations.AddField(
            model_name='spell',
            name='effect_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
