# Generated by Django 4.0.4 on 2022-06-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0004_alter_pictureimage_image'),
        ('users', '0004_remove_profile_character_name_copy'),
        ('rules', '0010_remove_weapon_weapon_type_delete_weapontype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weapon',
            new_name='WeaponType',
        ),
    ]
