# Generated by Django 4.0.4 on 2022-06-14 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_character_name_copy'),
        ('imaginarion', '0004_alter_pictureimage_image'),
        ('rules', '0011_rename_weapon_weapontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status__in', ['player', 'gm'])), related_name='allowed_weapon_types', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='picture_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weapon_types', to='imaginarion.pictureset'),
        ),
    ]
