# Generated by Django 3.1 on 2020-09-26 13:27

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0002_auto_20200926_1248'),
        ('rules', '0011_auto_20200926_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterProfession',
            new_name='Klass',
        ),
    ]
