# Generated by Django 3.2.8 on 2022-01-19 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_alter_skillgroup_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['factor', 'sign', 'value_number', 'value_percent', 'condition']},
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='value',
        ),
        migrations.AddField(
            model_name='modifier',
            name='sign',
            field=models.CharField(blank=True, choices=[('minus', 'minus'), ('plus', 'plus')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='value_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='modifier',
            name='value_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='condition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
