# Generated by Django 3.1 on 2020-09-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200926_1248'),
        ('rules', '0012_auto_20200926_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klass',
            options={'ordering': ['sorting_name'], 'verbose_name': 'Klass', 'verbose_name_plural': 'Klasses'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['sorting_name'], 'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.RenameField(
            model_name='eliteprofession',
            old_name='elite_class',
            new_name='elite_profession',
        ),
        migrations.AlterField(
            model_name='klass',
            name='allowed_profiles',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'active_player'), ('status', 'inactive_player'), ('status', 'inactive_player'), ('status', 'dead_player'), _connector='OR'), related_name='allowed_klasses', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='klasses', to='rules.profession'),
        ),
    ]
