# Generated by Django 4.0.4 on 2022-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0012_alter_weapontype_allowees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(choices=[('K', 'K'), ('S', 'S'), ('O', 'O'), ('K/S', 'K/S'), ('K/O', 'K/O'), ('O/S', 'O/S'), ('K/S/O', 'K/S/O')], max_length=10)),
                ('damage', models.CharField(max_length=15)),
            ],
            options={
                'ordering': ['type', 'description'],
            },
        ),
        migrations.AddField(
            model_name='weapontype',
            name='damage_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='weapon_types', to='rules.damagetype'),
        ),
    ]
