# Generated by Django 4.0.4 on 2022-06-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0013_damagetype_weapontype_damage_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagetype',
            name='special',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='damagetype',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='weapontype',
            name='special',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
