# Generated by Django 3.2.8 on 2022-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0013_alter_factor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
