# Generated by Django 4.0.4 on 2022-06-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0014_damagetype_special_alter_damagetype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagetype',
            name='range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='damagetype',
            name='special',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
