# Generated by Django 3.2.8 on 2022-01-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0015_perk_cost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['sign', 'value_number', 'value_percent', 'factor', 'condition']},
        ),
    ]
