# Generated by Django 4.0.4 on 2022-06-15 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_alter_weapontype_allowees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapontype',
            name='damage_bonus',
        ),
        migrations.RemoveField(
            model_name='weapontype',
            name='damage_dices',
        ),
        migrations.RemoveField(
            model_name='weapontype',
            name='damage_type',
        ),
        migrations.RemoveField(
            model_name='weapontype',
            name='range',
        ),
        migrations.RemoveField(
            model_name='weapontype',
            name='special',
        ),
    ]
