# Generated by Django 3.2.8 on 2022-01-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0016_alter_modifier_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='perk',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='perks', to='rules.RulesComment'),
        ),
    ]
