# Generated by Django 3.2.8 on 2022-01-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0017_auto_20220125_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
