# Generated by Django 4.0.4 on 2022-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0017_remove_weapontype_damage_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapontype',
            name='damage_types',
            field=models.ManyToManyField(related_name='weapon_types', to='rules.damagetype'),
        ),
    ]
