# Generated by Django 4.0.4 on 2022-06-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0018_alter_weapontype_damage_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapontype',
            name='comparables',
            field=models.ManyToManyField(blank=True, to='rules.weapontype'),
        ),
    ]
