# Generated by Django 3.2.8 on 2022-01-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0018_alter_perk_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilllevel',
            options={'ordering': ['sorting_name', 'id']},
        ),
    ]
