# Generated by Django 3.2.8 on 2022-01-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0019_alter_skilllevel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['sign', 'factor', 'value_number', 'value_percent', 'condition']},
        ),
    ]
