# Generated by Django 4.0.4 on 2022-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_character_name_copy'),
        ('rules', '0019_weapontype_comparables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='allowed_plates', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='allowed_shields', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status', 'player')), related_name='allowed_skills', to='users.profile'),
        ),
    ]
