# Generated by Django 4.0.4 on 2022-06-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0020_alter_plate_allowees_alter_shield_allowees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='diameter',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skilllevel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
