# Generated by Django 3.2.8 on 2022-01-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0021_modifier_value_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='rules.skill'),
        ),
        migrations.AlterField(
            model_name='synergylevel',
            name='synergy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synergy_levels', to='rules.synergy'),
        ),
    ]
