# Generated by Django 4.0.4 on 2022-06-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0021_skilllevel_diameter_skilllevel_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilllevel',
            old_name='diameter',
            new_name='radius',
        ),
    ]
