# Generated by Django 4.0.4 on 2022-06-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0022_rename_diameter_skilllevel_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='damage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
