# Generated by Django 3.2.8 on 2022-01-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0022_auto_20220129_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perk',
            old_name='modifiers',
            new_name='modifiers_old',
        ),
    ]
