# Generated by Django 4.0.4 on 2022-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0023_skilllevel_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='name_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_second',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
