# Generated by Django 3.2.8 on 2022-01-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0024_auto_20220129_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combattype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conditionalmodifier',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_modifier', to='rules.modifier'),
        ),
        migrations.AlterField(
            model_name='conditionalmodifier',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_modifier', to='rules.perk'),
        ),
    ]
