# Generated by Django 4.0.4 on 2022-07-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0024_skill_name_origin_skill_name_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='saving_throw_malus',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
