# Generated by Django 3.2.8 on 2022-01-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0025_auto_20220129_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalmodifier',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_modifiers', to='rules.modifier'),
        ),
        migrations.AlterField(
            model_name='conditionalmodifier',
            name='perk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_modifiers', to='rules.perk'),
        ),
    ]
