# Generated by Django 4.0.4 on 2022-07-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0026_skilllevel_saving_throw_trait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilllevel',
            name='saving_throw_trait',
            field=models.CharField(blank=True, choices=[('Sił', 'Sił'), ('Zrc', 'Zrc'), ('Kon', 'Kon'), ('Sił/Zrc', 'Sił/Zrc'), ('Sił/Kon', 'Sił/Kon'), ('Zrc/Kon', 'Zrc/Kon'), ('Sił/Zrc/Kon', 'Sił/Zrc/Kon')], max_length=20, null=True),
        ),
    ]
