# Generated by Django 3.2.8 on 2022-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0026_auto_20220129_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
