# Generated by Django 4.0.4 on 2022-07-02 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0027_alter_skilllevel_saving_throw_trait'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='damagetype',
            unique_together={('description', 'type', 'damage', 'special')},
        ),
        migrations.RemoveField(
            model_name='damagetype',
            name='range',
        ),
    ]
