# Generated by Django 4.0.4 on 2022-07-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0029_remove_modifier_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionalmodifier',
            name='overview',
        ),
    ]
