# Generated by Django 3.2.8 on 2022-01-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0029_remove_perk_modifiers_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['factor', 'sign', 'value_number', 'value_percent', 'value_text']},
        ),
        migrations.RemoveField(
            model_name='modifier',
            name='condition',
        ),
    ]
