# Generated by Django 3.2.8 on 2022-01-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0012_pictureset'),
        ('rules', '0031_auto_20220130_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shield',
            name='picture_sets',
        ),
        migrations.AddField(
            model_name='shield',
            name='picture_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shields', to='imaginarion.pictureset'),
        ),
    ]
