# Generated by Django 3.2.8 on 2022-01-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0032_auto_20220130_0739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modifier',
            unique_together={('factor', 'sign', 'value_number'), ('factor', 'sign', 'value_text'), ('factor', 'sign', 'value_percent')},
        ),
    ]
