# Generated by Django 3.2.8 on 2022-01-31 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0033_alter_modifier_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='mod_hiding_towns',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='mod_sneaking_towns',
        ),
    ]
