# Generated by Django 3.2.8 on 2022-01-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0035_auto_20220131_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='mod_climbing',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='mod_hiding',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='mod_lockpicking',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='mod_pickpocketing',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='mod_sneaking',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='mod_traps',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
