# Generated by Django 3.2.8 on 2022-02-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0036_auto_20220131_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='mod_max_agility',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='mod_max_movement',
        ),
    ]
