# Generated by Django 3.2.8 on 2022-02-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0037_auto_20220204_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
