# Generated by Django 3.2.8 on 2022-02-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0038_plate_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='plate',
            name='mod_conning',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='mod_listening',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='mod_lookout',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='mod_running',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='mod_swimming',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plate',
            name='mod_trailing',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
