# Generated by Django 3.2.8 on 2022-02-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0039_auto_20220210_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='modifiers',
            field=models.ManyToManyField(blank=True, related_name='perks', through='rules.ConditionalModifier', to='rules.Modifier'),
        ),
    ]
