# Generated by Django 4.0.2 on 2022-02-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0040_alter_perk_modifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combat_types', models.ManyToManyField(blank=True, related_name='bonuses', to='rules.CombatType')),
                ('conditions', models.ManyToManyField(blank=True, related_name='bonuses', to='rules.Condition')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='rules.modifier')),
            ],
            options={
                'ordering': ['modifier'],
            },
        ),
        migrations.AddField(
            model_name='perk',
            name='bonuses',
            field=models.ManyToManyField(blank=True, related_name='perks', to='rules.Bonus'),
        ),
    ]
