# Generated by Django 4.0.2 on 2022-02-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0042_remove_perk_modifiers_delete_conditionalmodifier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bonus',
            new_name='ConditionalModifier',
        ),
    ]
