# Generated by Django 4.0.2 on 2022-02-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0043_rename_bonus_conditionalmodifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perk',
            old_name='bonuses',
            new_name='conditional_modifiers',
        ),
        migrations.AlterField(
            model_name='conditionalmodifier',
            name='combat_types',
            field=models.ManyToManyField(blank=True, related_name='conditional_modifiers', to='rules.CombatType'),
        ),
        migrations.AlterField(
            model_name='conditionalmodifier',
            name='conditions',
            field=models.ManyToManyField(blank=True, related_name='conditional_modifiers', to='rules.Condition'),
        ),
        migrations.AlterField(
            model_name='conditionalmodifier',
            name='modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_modifiers', to='rules.modifier'),
        ),
    ]
