# Generated by Django 4.0.2 on 2022-02-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0044_rename_bonuses_perk_conditional_modifiers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionalmodifier',
            name='overview',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifier',
            name='overview',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
