# Generated by Django 4.0.2 on 2022-02-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0046_alter_modifier_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='sign',
            field=models.CharField(blank=True, choices=[('-', '-'), ('+', '+')], default='+', max_length=1, null=True),
        ),
    ]
