# Generated by Django 4.0.2 on 2022-02-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0047_alter_modifier_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perk',
            name='cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
