# Generated by Django 4.0.2 on 2022-02-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0048_alter_perk_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliteklass',
            old_name='allowed_profiles',
            new_name='allowees',
        ),
        migrations.RenameField(
            model_name='eliteprofession',
            old_name='allowed_profiles',
            new_name='allowees',
        ),
        migrations.RenameField(
            model_name='klass',
            old_name='allowed_profiles',
            new_name='allowees',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='allowed_profiles',
            new_name='allowees',
        ),
        migrations.RenameField(
            model_name='shield',
            old_name='allowed_profiles',
            new_name='allowees',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='allowed_profiles',
            new_name='allowees',
        ),
        migrations.RenameField(
            model_name='synergy',
            old_name='allowed_profiles',
            new_name='allowees',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='allowed_profiles',
            new_name='allowees',
        ),
    ]
