# Generated by Django 4.0.2 on 2022-02-14 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imaginarion', '0012_pictureset'),
        ('rules', '0052_remove_plate_picture_sets_remove_weapon_picture_sets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='picture_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plates', to='imaginarion.pictureset'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='picture_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weapons', to='imaginarion.pictureset'),
        ),
    ]
