# Generated by Django 4.0.2 on 2022-02-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0053_alter_plate_picture_set_alter_weapon_picture_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='damage_big_add',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='damage_big_dices',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='delay',
        ),
    ]
