# Generated by Django 4.0.2 on 2022-02-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0054_remove_weapon_damage_big_add_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='damage_small_add',
            new_name='damage_bonus',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='damage_small_dices',
            new_name='damage_dices',
        ),
    ]
