# Generated by Django 4.0.2 on 2022-02-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0055_rename_damage_small_add_weapon_damage_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionalmodifier',
            name='overview',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modifier',
            name='overview',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
