# Generated by Django 4.0.2 on 2022-02-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_options'),
        ('rules', '0056_alter_conditionalmodifier_overview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionalmodifier',
            options={'ordering': ['overview']},
        ),
        migrations.AlterField(
            model_name='eliteklass',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status__in', ['player', 'gm'])), related_name='allowed_elite_klasses', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='eliteprofession',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status__in', ['player', 'gm'])), related_name='allowed_elite_classes', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='klass',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status__in', ['player', 'gm'])), related_name='allowed_klasses', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='plate',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status__in', ['player', 'gm'])), related_name='allowed_plates', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status__in', ['player', 'gm'])), related_name='allowed_shields', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status__in', ['player', 'gm'])), related_name='allowed_skills', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='allowees',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('status__in', ['player', 'gm'])), related_name='allowed_weapons', to='users.Profile'),
        ),
    ]
