# Generated by Django 2.2.1 on 2020-03-25 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_ended', models.BooleanField(default=False)),
                ('is_individual', models.BooleanField(default=False)),
                ('allowed_profiles', models.ManyToManyField(related_name='allowed_debates', to='users.Profile')),
                ('followers', models.ManyToManyField(blank=True, related_name='followed_debates', to='users.Profile')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('allowed_profiles', models.ManyToManyField(blank=True, related_name='allowed_topics', to='users.Profile')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4000)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_pics')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to=settings.AUTH_USER_MODEL)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='debates.Debate')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='remarks_seen', to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='debates.Topic'),
        ),
    ]
