# Generated by Django 2.2.1 on 2020-03-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debate',
            name='starter',
        ),
    ]
