# Generated by Django 2.2.1 on 2020-06-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0003_auto_20200623_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debate',
            options={'ordering': ['-date_created']},
        ),
    ]
