# Generated by Django 2.2.1 on 2020-07-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('debates', '0004_auto_20200628_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debate',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='debate',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='remark',
            old_name='date_posted',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='debate',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='allowed_profiles',
        ),
        migrations.AddField(
            model_name='debate',
            name='known_directly',
            field=models.ManyToManyField(related_name='debates_known_directly', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='debate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='remark',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
