# Generated by Django 4.0.4 on 2023-01-27 18:34

import _todos.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fiber', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('monthdate', models.TextField(default=_todos.models.monthdate, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-monthdate'],
            },
        ),
        migrations.CreateModel(
            name='TODOList',
            fields=[
                ('daydate', models.DateField(default=datetime.date.today, primary_key=True, serialize=False)),
                ('SUNWALK', models.BooleanField(default=False)),
                ('MED', models.BooleanField(default=False)),
                ('MED2', models.BooleanField(default=False)),
                ('MED3', models.BooleanField(default=False)),
                ('TETRIS', models.BooleanField(default=False)),
                ('RELAX', models.BooleanField(default=False)),
                ('sleep', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('IForKETO', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('drinkfood', models.BooleanField(default=False)),
                ('flaxseed', models.BooleanField(default=False)),
                ('spirulina', models.BooleanField(default=False)),
                ('lionsmane', models.BooleanField(default=False)),
                ('pickles', models.BooleanField(default=False)),
                ('fishoilord3', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('coffeex2', models.BooleanField(default=False)),
                ('noA', models.PositiveSmallIntegerField(default=0)),
                ('warmup', models.BooleanField(default=False)),
                ('stretching', models.BooleanField(default=False)),
                ('workout', models.TextField(blank=True, null=True)),
                ('MicroW', models.TextField(blank=True, null=True)),
                ('Mass', models.TextField(blank=True, null=True)),
                ('ISO', models.TextField(blank=True, null=True)),
                ('Cardio', models.TextField(blank=True, null=True)),
                ('RPG', models.BooleanField(default=False)),
                ('CODE', models.BooleanField(default=False)),
                ('ENG', models.BooleanField(default=False)),
                ('DE', models.BooleanField(default=False)),
                ('FR', models.BooleanField(default=False)),
                ('UKR', models.BooleanField(default=False)),
                ('awareness', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('happiness', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('openness', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('focus', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('anger', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('fear', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('emptiness', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('chaos', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('month', models.ForeignKey(default=_todos.models.thismonth, on_delete=django.db.models.deletion.PROTECT, related_name='days', to='_todos.month')),
            ],
            options={
                'ordering': ['-daydate'],
            },
        ),
        migrations.CreateModel(
            name='TODOList2022',
            fields=[
            ],
            options={
                'verbose_name': 'TODO 2022',
                'verbose_name_plural': 'TODOs 2022',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('_todos.todolist',),
        ),
        migrations.CreateModel(
            name='TODOList2023',
            fields=[
            ],
            options={
                'verbose_name': 'TODO 2023',
                'verbose_name_plural': 'TODOs 2023',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('_todos.todolist',),
        ),
    ]
