# Generated by Django 4.0.4 on 2022-12-25 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODOList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daydate', models.DateField(default=datetime.date.today, unique=True)),
                ('SUNWALK', models.BooleanField(default=False)),
                ('MED', models.BooleanField(default=False)),
                ('TETRIS', models.BooleanField(default=False)),
                ('RELAX', models.BooleanField(default=False)),
                ('sleep', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('IForKETO', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('drinkfood', models.BooleanField(default=False)),
                ('flaxseed', models.BooleanField(default=False)),
                ('spirulina', models.BooleanField(default=False)),
                ('lionsmane', models.BooleanField(default=False)),
                ('pickles', models.BooleanField(default=False)),
                ('fishoilord3', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('coffeex2', models.BooleanField(default=False)),
                ('noA', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('warmup', models.BooleanField(default=False)),
                ('stretching', models.BooleanField(default=False)),
                ('workout', models.TextField(blank=True, null=True)),
                ('CODE', models.BooleanField(default=False)),
                ('ENG', models.BooleanField(default=False)),
                ('DE', models.BooleanField(default=False)),
                ('FR', models.BooleanField(default=False)),
                ('UKR', models.BooleanField(default=False)),
                ('awareness', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('happiness', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('openness', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('focus', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('anger', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('fear', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('emptiness', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('chaos', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-daydate'],
            },
        ),
    ]
