# Generated by Django 4.0.4 on 2023-01-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TODOList2021',
            fields=[
            ],
            options={
                'verbose_name': 'TODO 2021',
                'verbose_name_plural': 'TODOs 2021',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('_todos.todolist',),
        ),
        migrations.AlterModelOptions(
            name='todolist2023',
            options={'ordering': ['-daydate'], 'verbose_name': 'TODO 2023', 'verbose_name_plural': 'TODOs 2023'},
        ),
        migrations.AddField(
            model_name='todolist',
            name='DREAMS',
            field=models.TextField(blank=True, null=True),
        ),
    ]
