# Generated by Django 4.1.4 on 2023-01-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_todos', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='noA',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
